using System.Text.Json;
using LeagueAkari.WinUI.Services;
int checks = 0;
void Check(bool valid, string message) { if (!valid) throw new Exception(message); checks++; }
JsonElement J(object? value) => JsonSerializer.SerializeToElement(value);
var definitions = J(new Dictionary<string, object> { ["420"] = new { id = 420, name = "Solo" }, ["440"] = new { id = 440, name = "Flex" }, ["9999"] = new { id = 9999, name = "Custom tag" } });
var self = J(new[] { new { queueId = 420 }, new { queueId = 440 } }); var party = J(new[] { new { queueId = 440 } });
var queues = ToolkitLobbyData.Queues(definitions, self, party);
Check(queues.Select(queue => queue.Id).SequenceEqual(new[] { 440, 420, 9999 }), "Eligibility needs self and party; group order preserves source");
Check(queues.Single(queue => queue.Id == 420).Eligible == false, "Self-only eligible is not party eligible");
Check(ToolkitLobbyData.ValidQueue(987654), "Arbitrary non-catalog queue is accepted");
Check(!ToolkitLobbyData.ValidQueue(double.NaN) && !ToolkitLobbyData.ValidQueue(0) && !ToolkitLobbyData.ValidQueue(1.5) && !ToolkitLobbyData.ValidQueue(double.PositiveInfinity), "Reject malformed queue IDs");
var client = J(new { connectionState = "connected" }); var lobby = J(new { lobby = new { gameConfig = new { gameMode = "STRAWBERRY" } } });
Check(ToolkitLobbyData.IsSwarm(client, lobby), "Swarm lobby available");
Check(!ToolkitLobbyData.IsSwarm(J(new { connectionState = "disconnected" }), lobby), "Disconnect blocks Swarm writes");
Check(!ToolkitLobbyData.IsSwarm(client, J(new { lobby = new { gameConfig = new { gameMode = "ARAM" } } })), "Ordinary lobby hides Swarm form");
var champions = ToolkitLobbyData.Champions(J(new[] { new { id = 222, name = "Jinx" }, new { id = 4000, name = "Other" }, new { id = 3000, name = "Swarm A" }, new { id = 3999, name = "Swarm B" } }));
Check(champions.Select(hero => hero.Id).SequenceEqual(new[] { 3000, 3999, 222, 4000 }), "Original maybePveChampion exact boundaries and group sort");
var maps = ToolkitLobbyData.Maps(J(new[] { new { MapDisplayInfoList = new[] { new { value = new { Name = "Outskirts", Map = new { ContentId = "map-content", ItemId = 8 } } } } } }));
Check(maps.Single() == new SwarmMap("Outskirts", "map-content", 8), "Original hub map name/content/item contract");
var slots = J(ToolkitLobbyData.Slots(3000, null, null)).Items().Single();
Check(slots.Number("spell1") == 1 && slots.Number("spell2") == 1 && slots.Text("positionPreference") == "UNSELECTED", "Hero selection defaults absent map and difficulty to 1");
var selected = J(ToolkitLobbyData.Slots(3000, maps.Single(), 3)).Items().Single();
Check(selected.Number("championId") == 3000 && selected.Number("spell1") == 8 && selected.Number("spell2") == 3, "Hero write uses selected map and difficulty");
var app = J(new { isElevated = false, nativeSupport = new { nativeInput = new { available = false, requiresElevation = true, availableOnCurrentPlatform = true } } });
Check(ToolkitClientData.Requirement(app, "nativeInput") == new ToolkitNativeRequirement(false, true, true), "Administrator explanation uses platform availability and elevation independently");
Check(!ToolkitClientData.Requirement(J(new { isElevated = true, nativeSupport = new { nativeInput = new { available = true, requiresElevation = true, availableOnCurrentPlatform = true } } }), "nativeInput").NeedsElevation, "Elevated capability avoids admin warning");
Check(ToolkitClientData.FileMode(J("readonly")) == "readonly" && ToolkitClientData.FileMode(J("writable")) == "writable", "Known file modes read back");
Check(ToolkitClientData.FileMode(J(null)) == "unavailable" && ToolkitClientData.FileMode(J("unknown")) == "unavailable", "Unknown/missing file state cannot display writable");
Console.WriteLine($"{checks} original Client/Lobby behavior fixtures passed.");
