import type { RenderGroup, RenderGroupOptions } from './types'

export const RENDER_GROUP_DISPLAY_ORDER = [
  'combat-stats',
  'akari',
  'game-state',
  'misc',
  'damage',
  'cc',
  'vision',
  'buildings',
  'objectives',
  'economy',
  'healing',
  'pings',
  'combat-advanced',
  'statistics',
  'abilities',
  'survival-skills',
  'teamfight',
  'ignored',
  'undocumented'
]

export const RENDER_GROUPS: RenderGroup[] = [
  {
    group: 'combat-stats',
    items: [
      { key: 'kills', render: 'integer' },
      { key: 'deaths', render: 'integer' },
      { key: 'assists', render: 'integer' },
      { key: 'firstBloodKill', render: 'boolean' },
      { key: 'firstBloodAssist', render: 'boolean' },
      { key: 'doubleKills', render: 'integer' },
      { key: 'tripleKills', render: 'integer' },
      { key: 'quadraKills', render: 'integer' },
      { key: 'pentaKills', render: 'integer' },
      { key: 'unrealKills', render: 'integer' },
      { key: 'killingSprees', render: 'integer' },
      { key: 'largestKillingSpree', render: 'integer' },
      { key: 'largestMultiKill', render: 'integer' },
      { key: 'longestTimeSpentLiving', render: 'integer' },
      { key: 'largestCriticalStrike', render: 'integer' },
      { key: 'legendaryCount', render: 'integer' },
      { key: 'highestChampionDamage', render: 'boolean' },
      { key: 'damageGoldEfficiency', render: 'percentage' }
    ]
  },
  {
    group: 'akari',
    items: [{ key: 'akariScore', render: 'akari-score' }]
  },
  {
    group: 'damage',
    items: [
      { key: 'totalDamageDealtToChampions', render: 'compat' },
      { key: 'physicalDamageDealtToChampions', render: 'compat' },
      { key: 'magicDamageDealtToChampions', render: 'compat' },
      { key: 'trueDamageDealtToChampions', render: 'compat' },
      { key: 'totalDamageDealt', render: 'compat' },
      { key: 'physicalDamageDealt', render: 'compat' },
      { key: 'magicDamageDealt', render: 'compat' },
      { key: 'trueDamageDealt', render: 'compat' },
      { key: 'damageDealtToObjectives', render: 'compat' },
      { key: 'damageDealtToTurrets', render: 'compat' },
      { key: 'damageDealtToBuildings', render: 'compat' },
      { key: 'damageDealtToEpicMonsters', render: 'compat' },
      { key: 'totalDamageTaken', render: 'compat' },
      { key: 'physicalDamageTaken', render: 'compat' },
      { key: 'magicDamageTaken', render: 'compat' },
      { key: 'magicalDamageTaken', render: 'compat' },
      { key: 'trueDamageTaken', render: 'compat' },
      { key: 'damageSelfMitigated', render: 'compat' },
      { key: 'totalDamageShieldedOnTeammates', render: 'compat' }
    ]
  },
  {
    group: 'cc',
    items: [
      { key: 'timeCCingOthers', render: 'integer' },
      { key: 'totalTimeCCDealt', render: 'integer' },
      { key: 'totalTimeCrowdControlDealt', render: 'integer' },
      { key: 'enemyChampionImmobilizations', render: 'integer' },
      { key: 'immobilizeAndKillWithAlly', render: 'integer' },
      { key: 'knockEnemyIntoTeamAndKill', render: 'integer' },
      { key: 'survivedThreeImmobilizesInFight', render: 'integer' },
      { key: 'highestCrowdControlScore', render: 'integer' }
    ]
  },
  {
    group: 'vision',
    items: [
      { key: 'visionScore', render: 'integer' },
      { key: 'wardsPlaced', render: 'integer' },
      { key: 'wardsKilled', render: 'integer' },
      { key: 'sightWardsBoughtInGame', render: 'integer' },
      { key: 'visionWardsBoughtInGame', render: 'integer' },
      { key: 'detectorWardsPlaced', render: 'integer' },
      { key: 'visionScorePerMinute', render: 'integer' },
      { key: 'wardTakedowns', render: 'integer' },
      { key: 'wardTakedownsBefore20M', render: 'integer' },
      { key: 'wardsGuarded', render: 'integer' },
      { key: 'twoWardsOneSweeperCount', render: 'integer' },
      { key: 'controlWardsPlaced', render: 'integer' },
      { key: 'stealthWardsPlaced', render: 'integer' },
      { key: 'visionScoreAdvantageLaneOpponent', render: 'float' }
    ]
  },
  {
    group: 'buildings',
    items: [
      { key: 'turretKills', render: 'integer' },
      { key: 'turretTakedowns', render: 'integer' },
      { key: 'soloTurretsLategame', render: 'integer' },
      { key: 'turretsLost', render: 'integer' },
      { key: 'firstTowerKill', render: 'boolean' },
      { key: 'firstTowerAssist', render: 'boolean' },
      { key: 'firstTurretKilled', render: 'integer' },
      { key: 'firstTurretKilledTime', render: 'game-time' },
      { key: 'turretPlatesTaken', render: 'integer' },
      { key: 'kTurretsDestroyedBeforePlatesFall', render: 'integer' },
      { key: 'outerTurretExecutesBefore10Minutes', render: 'integer' },
      { key: 'quickFirstTurret', render: 'integer' },
      { key: 'takedownOnFirstTurret', render: 'integer' },
      { key: 'turretsTakenWithRiftHerald', render: 'integer' },
      { key: 'multiTurretRiftHeraldCount', render: 'integer' },
      { key: 'inhibitorKills', render: 'integer' },
      { key: 'inhibitorTakedowns', render: 'integer' },
      { key: 'inhibitorsLost', render: 'integer' },
      { key: 'firstInhibitorKill', render: 'boolean' },
      { key: 'firstInhibitorAssist', render: 'boolean' },
      { key: 'lostAnInhibitor', render: 'integer' },
      { key: 'nexusKills', render: 'integer' },
      { key: 'nexusLost', render: 'integer' },
      { key: 'nexusTakedowns', render: 'integer' },
      { key: 'hadOpenNexus', render: 'boolean' },
      { key: 'outnumberedNexusKill', render: 'integer' },
      { key: 'objectivesStolen', render: 'integer' },
      { key: 'objectivesStolenAssists', render: 'integer' }
    ]
  },
  {
    group: 'economy',
    items: [
      { key: 'goldEarned', render: 'compat' },
      { key: 'goldSpent', render: 'compat' },
      { key: 'bountyGold', render: 'integer' },
      { key: 'totalMinionsKilled', render: 'integer' },
      { key: 'laneMinionsFirst10Minutes', render: 'integer' },
      { key: 'twentyMinionsIn3SecondsCount', render: 'integer' },
      { key: 'neutralMinionsKilled', render: 'integer' },
      { key: 'neutralMinionsKilledEnemyJungle', render: 'integer' },
      { key: 'neutralMinionsKilledTeamJungle', render: 'integer' },
      { key: 'totalAllyJungleMinionsKilled', render: 'integer' },
      { key: 'totalEnemyJungleMinionsKilled', render: 'integer' },
      { key: 'consumablesPurchased', render: 'integer' },
      { key: 'itemsPurchased', render: 'integer' },
      { key: 'earlyLaningPhaseGoldExpAdvantage', render: 'integer' },
      { key: 'laningPhaseGoldExpAdvantage', render: 'integer' },
      { key: 'maxCsAdvantageOnLaneOpponent', render: 'integer' },
      { key: 'completeSupportQuestInTime', render: 'integer' },
      { key: 'mejaisFullStackInTime', render: 'integer' }
    ]
  },
  {
    group: 'healing',
    items: [
      { key: 'totalHeal', render: 'compat' },
      { key: 'totalUnitsHealed', render: 'integer' },
      { key: 'totalHealsOnTeammates', render: 'compat' },
      { key: 'effectiveHealAndShielding', render: 'compat' },
      { key: 'HealFromMapSources', render: 'compat' }
    ]
  },
  {
    group: 'pings',
    items: [
      { key: 'allInPings', render: 'integer' },
      { key: 'assistMePings', render: 'integer' },
      { key: 'basicPings', render: 'integer' },
      { key: 'commandPings', render: 'integer' },
      { key: 'dangerPings', render: 'integer' },
      { key: 'enemyMissingPings', render: 'integer' },
      { key: 'enemyVisionPings', render: 'integer' },
      { key: 'getBackPings', render: 'integer' },
      { key: 'holdPings', render: 'integer' },
      { key: 'needVisionPings', render: 'integer' },
      { key: 'onMyWayPings', render: 'integer' },
      { key: 'pushPings', render: 'integer' },
      { key: 'retreatPings', render: 'integer' },
      { key: 'visionClearedPings', render: 'integer' }
    ]
  },
  {
    group: 'combat-advanced',
    items: [
      { key: 'soloKills', render: 'integer' },
      { key: 'quickSoloKills', render: 'integer' },
      { key: 'takedowns', render: 'integer' },
      { key: 'outnumberedKills', render: 'integer' },
      { key: 'multikills', render: 'integer' },
      { key: 'multikillsAfterAggressiveFlash', render: 'integer' },
      { key: 'multiKillOneSpell', render: 'integer' },
      { key: 'killAfterHiddenWithAlly', render: 'integer' },
      { key: 'pickKillWithAlly', render: 'integer' },
      { key: 'killsWithHelpFromEpicMonster', render: 'integer' },
      { key: 'takedownsBeforeJungleMinionSpawn', render: 'integer' },
      { key: 'takedownsFirstXMinutes', render: 'integer' },
      { key: 'takedownsAfterGainingLevelAdvantage', render: 'integer' },
      { key: 'maxKillDeficit', render: 'integer' },
      { key: 'maxLevelLeadLaneOpponent', render: 'integer' },
      { key: 'takedownsInAlcove', render: 'integer' },
      { key: 'takedownsInEnemyFountain', render: 'integer' },
      { key: 'killsNearEnemyTurret', render: 'integer' },
      { key: 'killsUnderOwnTurret', render: 'integer' },
      { key: 'killsOnOtherLanesEarlyJungleAsLaner', render: 'integer' },
      { key: 'getTakedownsInAllLanesEarlyJungleAsLaner', render: 'integer' },
      { key: 'killsOnRecentlyHealedByAramPack', render: 'integer' }
    ]
  },
  {
    group: 'objectives',
    items: [
      { key: 'baronTakedowns', render: 'integer' },
      { key: 'baronBuffGoldAdvantageOverThreshold', render: 'integer' },
      { key: 'earliestBaron', render: 'game-time' },
      { key: 'earliestDragonTakedown', render: 'game-time' },
      { key: 'dragonTakedowns', render: 'integer' },
      { key: 'riftHeraldTakedowns', render: 'integer' },
      { key: 'teamBaronKills', render: 'integer' },
      { key: 'teamElderDragonKills', render: 'integer' },
      { key: 'teamRiftHeraldKills', render: 'integer' },
      { key: 'soloBaronKills', render: 'integer' },
      { key: 'elderDragonKillsWithOpposingSoul', render: 'integer' },
      { key: 'elderDragonMultikills', render: 'integer' },
      { key: 'perfectDragonSoulsTaken', render: 'integer' },
      { key: 'epicMonsterSteals', render: 'integer' },
      { key: 'epicMonsterStolenWithoutSmite', render: 'integer' },
      { key: 'epicMonsterKillsNearEnemyJungler', render: 'integer' },
      { key: 'epicMonsterKillsWithin30SecondsOfSpawn', render: 'integer' },
      { key: 'junglerTakedownsNearDamagedEpicMonster', render: 'integer' },
      { key: 'voidMonsterKill', render: 'integer' },
      { key: 'alliedJungleMonsterKills', render: 'integer' },
      { key: 'enemyJungleMonsterKills', render: 'integer' },
      { key: 'scuttleCrabKills', render: 'integer' },
      { key: 'buffsStolen', render: 'integer' },
      { key: 'jungleCsBefore10Minutes', render: 'integer' },
      { key: 'initialBuffCount', render: 'integer' },
      { key: 'initialCrabCount', render: 'integer' },
      { key: 'moreEnemyJungleThanOpponent', render: 'integer' },
      { key: 'baronKills', render: 'integer' },
      { key: 'dragonKills', render: 'integer' }
    ]
  },
  {
    group: 'statistics',
    items: [
      { key: 'kda', render: 'float' },
      { key: 'killParticipation', render: 'percentage' },
      { key: 'damagePerMinute', render: 'compat' },
      { key: 'goldPerMinute', render: 'compat' },
      { key: 'damageTakenOnTeamPercentage', render: 'integer' },
      { key: 'teamDamagePercentage', render: 'integer' }
    ]
  },
  {
    group: 'abilities',
    items: [
      { key: 'abilityUses', render: 'integer' },
      { key: 'spell1Casts', render: 'integer' },
      { key: 'spell2Casts', render: 'integer' },
      { key: 'spell3Casts', render: 'integer' },
      { key: 'spell4Casts', render: 'integer' },
      { key: 'summoner1Casts', render: 'integer' },
      { key: 'summoner2Casts', render: 'integer' }
    ]
  },
  {
    group: 'survival-skills',
    items: [
      { key: 'deathsByEnemyChamps', render: 'integer' },
      { key: 'survivedSingleDigitHpCount', render: 'integer' },
      { key: 'tookLargeDamageSurvived', render: 'integer' },
      { key: 'killedChampTookFullTeamDamageSurvived', render: 'integer' },
      { key: 'saveAllyFromDeath', render: 'integer' },
      { key: 'skillshotsDodged', render: 'integer' },
      { key: 'skillshotsHit', render: 'integer' },
      { key: 'snowballsHit', render: 'integer' },
      { key: 'dodgeSkillShotsSmallWindow', render: 'integer' },
      { key: 'landSkillShotsEarlyGame', render: 'integer' },
      { key: 'blastConeOppositeOpponentCount', render: 'integer' },
      { key: 'quickCleanse', render: 'integer' },
      { key: 'dancedWithRiftHerald', render: 'integer' },
      { key: 'fistBumpParticipation', render: 'integer' }
    ]
  },
  {
    group: 'teamfight',
    items: [
      { key: 'flawlessAces', render: 'integer' },
      { key: 'doubleAces', render: 'integer' },
      { key: 'acesBefore15Minutes', render: 'integer' },
      { key: 'fullTeamTakedown', render: 'integer' },
      { key: 'shortestTimeToAceFromFirstTakedown', render: 'game-time' },
      { key: '12AssistStreakCount', render: 'integer' },
      { key: 'teleportTakedowns', render: 'integer' }
    ]
  },
  {
    group: 'game-state',
    items: [
      { key: 'gameEndedInEarlySurrender', render: 'boolean' },
      { key: 'gameEndedInIGNBSurrender', render: 'boolean' },
      { key: 'gameEndedInSurrender', render: 'boolean' },
      { key: 'causedEarlySurrender', render: 'boolean', hide: true },
      { key: 'causedGameEndFromIGNBSurrender', render: 'boolean' },
      { key: 'earlySurrenderAccomplice', render: 'boolean', hide: true },
      { key: 'teamEarlySurrendered', render: 'boolean' },
      { key: 'teamIGNBSurrendered', render: 'boolean' },
      { key: 'wasPremadeWithIGNBGameEndCauser', render: 'boolean' },
      { key: 'wasPremadeWithSevereTransgressor', render: 'boolean' },
      { key: 'wasSevereTransgressor', render: 'boolean' },
      { key: 'hadAfkTeammate', render: 'boolean' },
      { key: 'PlayerBehavior_IsHeroInCombat', render: 'boolean' },
      { key: 'positionAssignedByMatchmaking', render: 'position' },
      { key: 'selectedRolePreferences', render: 'selectedRole' },
      { key: 'playedChampSelectPosition', render: 'integer', hide: true },
      { key: 'PlayerBehavior', hide: true }
    ]
  },
  {
    group: 'misc',
    items: [
      { key: 'champLevel', render: 'integer' },
      { key: 'champExperience', render: 'compat' },
      { key: 'timePlayed', render: 'integer' },
      { key: 'totalTimeSpentDead', render: 'integer' },
      { key: 'unseenRecalls', render: 'integer' },
      { key: 'perfectGame', render: 'integer' },
      { key: 'gameLength', render: 'game-time' }
    ]
  },
  {
    group: 'ignored',
    items: [
      { key: 'identity', hide: true },
      { key: 'championId', hide: true },
      { key: 'championName', hide: true },
      { key: 'championTransform', hide: true },
      { key: 'participantId', hide: true },
      { key: 'teamId', hide: true },
      { key: 'puuid', hide: true },
      { key: 'summonerId', hide: true },
      { key: 'summonerName', hide: true },
      { key: 'summonerLevel', hide: true },
      { key: 'profileIcon', hide: true },
      { key: 'riotIdGameName', hide: true },
      { key: 'riotIdTagline', hide: true },
      { key: 'lane', hide: true },
      { key: 'role', hide: true },
      { key: 'teamPosition', hide: true },
      { key: 'individualPosition', hide: true },
      { key: 'placement', hide: true },
      { key: 'subteamPlacement', hide: true },
      { key: 'playerSubteamId', hide: true },
      { key: 'item0', hide: true },
      { key: 'item1', hide: true },
      { key: 'item2', hide: true },
      { key: 'item3', hide: true },
      { key: 'item4', hide: true },
      { key: 'item5', hide: true },
      { key: 'item6', hide: true },
      { key: 'roleBoundItem', hide: true },
      { key: 'playerAugment1', hide: true },
      { key: 'playerAugment2', hide: true },
      { key: 'playerAugment3', hide: true },
      { key: 'playerAugment4', hide: true },
      { key: 'playerAugment5', hide: true },
      { key: 'playerAugment6', hide: true },
      { key: 'perks', hide: true },
      { key: 'perk0', hide: true },
      { key: 'perk0Var1', hide: true },
      { key: 'perk0Var2', hide: true },
      { key: 'perk0Var3', hide: true },
      { key: 'perk1', hide: true },
      { key: 'perk1Var1', hide: true },
      { key: 'perk1Var2', hide: true },
      { key: 'perk1Var3', hide: true },
      { key: 'perk2', hide: true },
      { key: 'perk2Var1', hide: true },
      { key: 'perk2Var2', hide: true },
      { key: 'perk2Var3', hide: true },
      { key: 'perk3', hide: true },
      { key: 'perk3Var1', hide: true },
      { key: 'perk3Var2', hide: true },
      { key: 'perk3Var3', hide: true },
      { key: 'perk4', hide: true },
      { key: 'perk4Var1', hide: true },
      { key: 'perk4Var2', hide: true },
      { key: 'perk4Var3', hide: true },
      { key: 'perk5', hide: true },
      { key: 'perk5Var1', hide: true },
      { key: 'perk5Var2', hide: true },
      { key: 'perk5Var3', hide: true },
      { key: 'perkPrimaryStyle', hide: true },
      { key: 'perkSubStyle', hide: true },
      { key: 'PlayerScore0', hide: true },
      { key: 'PlayerScore1', hide: true },
      { key: 'PlayerScore2', hide: true },
      { key: 'PlayerScore3', hide: true },
      { key: 'PlayerScore4', hide: true },
      { key: 'PlayerScore5', hide: true },
      { key: 'PlayerScore6', hide: true },
      { key: 'PlayerScore7', hide: true },
      { key: 'PlayerScore8', hide: true },
      { key: 'PlayerScore9', hide: true },
      { key: 'PlayerScore10', hide: true },
      { key: 'PlayerScore11', hide: true },
      { key: 'playerScore0', hide: true },
      { key: 'playerScore1', hide: true },
      { key: 'playerScore2', hide: true },
      { key: 'playerScore3', hide: true },
      { key: 'playerScore4', hide: true },
      { key: 'playerScore5', hide: true },
      { key: 'playerScore6', hide: true },
      { key: 'playerScore7', hide: true },
      { key: 'playerScore8', hide: true },
      { key: 'playerScore9', hide: true },
      { key: 'combatPlayerScore', hide: true },
      { key: 'objectivePlayerScore', hide: true },
      { key: 'totalPlayerScore', hide: true },
      { key: 'totalScoreRank', hide: true },
      { key: 'win', hide: true },
      { key: 'eligibleForProgression', hide: true },
      { key: 'InfernalScalePickup', hide: true },
      { key: 'SWARM_DefeatAatrox', hide: true },
      { key: 'SWARM_DefeatBriar', hide: true },
      { key: 'SWARM_DefeatMiniBosses', hide: true },
      { key: 'SWARM_EvolveWeapon', hide: true },
      { key: 'SWARM_Have3Passives', hide: true },
      { key: 'SWARM_KillEnemy', hide: true },
      { key: 'SWARM_PickupGold', hide: true },
      { key: 'SWARM_ReachLevel50', hide: true },
      { key: 'SWARM_Survive15Min', hide: true },
      { key: 'SWARM_WinWith5EvolvedWeapons', hide: true },
      { key: 'poroExplosions', hide: true },
      { key: 'spell1Id', hide: true },
      { key: 'spell2Id', hide: true },
      { key: 'legendaryItemUsed', hide: true }
    ]
  }
]

export const MAPPED_RENDER_GROUP_OPTIONS = RENDER_GROUPS.reduce(
  (acc, group) => {
    group.items.forEach((item: RenderGroupOptions) => {
      acc[item.key] = {
        key: item.key,
        render: item.render,
        hide: item.hide,
        group: group.group
      }
    })
    return acc
  },
  {} as Record<string, RenderGroupOptions & { group: string }>
)
