using System.Text.Json;
using LeagueAkari.WinUI.Services;

int passed = 0;
void Check(string label, bool condition) { if (!condition) throw new InvalidOperationException(label); Console.WriteLine("PASS " + label); passed++; }
JsonElement Json(string json) => JsonDocument.Parse(json).RootElement.Clone();
MatchParticipant Participant(string json) { var raw = Json(json); var stats = raw.Field("stats"); return new(raw, stats.ValueKind == JsonValueKind.Object ? stats : raw, raw.Text("puuid"), "name", "tag", 1, 103, 100, "TEAM-100", "", "win"); }
var missing = Participant("{\"puuid\":\"a\",\"stats\":{\"kills\":0,\"deaths\":0,\"assists\":0,\"totalMinionsKilled\":0}}");
Check("LCU supplied zero remains zero", MatchDetailsData.Stat(missing,"kills") == 0);
Check("LCU absent gold remains unknown", MatchDetailsData.Stat(missing,"goldEarned") == null);
Check("Incomplete LCU CS is not fabricated", MatchDetailsData.Stat(missing,"cs") == null);
Check("Zero-death KDA uses upstream divisor", MatchDetailsData.Stat(missing,"kda") == 0);
Check("Missing gold does not produce 0% damage efficiency", MatchDetailsData.Stat(missing,"damageGoldEfficiency") == null);
var sgp = Participant("{\"puuid\":\"b\",\"totalDamageDealtToChampions\":12000,\"goldEarned\":6000,\"totalMinionsKilled\":20,\"neutralMinionsKilled\":0,\"challenges\":{\"soloKills\":0}}");
Check("SGP derived efficiency preserves inputs", MatchDetailsData.Stat(sgp,"damageGoldEfficiency") == 2);
Check("SGP zero challenge is available", MatchDetailsData.Stat(sgp,"soloKills") == 0);
Check("SGP full CS adds lane and jungle", MatchDetailsData.Stat(sgp,"cs") == 20);
Check("Unknown totals remain unknown", MatchDetailsData.Sum([1, null]) == null);
Check("Unavailable stat formats as em dash", MatchDetailsData.Format(null) == "—");
var lcuFrame = Json("{\"participantFrames\":{\"1\":{\"totalGold\":0,\"minionsKilled\":0,\"jungleMinionsKilled\":0}}}");
Check("LCU timeline zero gold is a data point", MatchDetailsData.TimelineMetric(lcuFrame,1,0) == 0);
Check("LCU missing XP remains a gap", MatchDetailsData.TimelineMetric(lcuFrame,1,2) == null);
Check("LCU unsupported damage is not a zero curve", MatchDetailsData.TimelineMetric(lcuFrame,1,3) == null);
Check("Missing participant timeline stays unknown", MatchDetailsData.TimelineMetric(lcuFrame,2,0) == null);
Check("Simulation rejects missing PUUID", !MatchDetailsData.HasDraftIdentities([missing with { Puuid="" }]));
Check("Simulation rejects duplicate PUUID", !MatchDetailsData.HasDraftIdentities([missing,missing]));
Check("Simulation accepts complete unique identities", MatchDetailsData.HasDraftIdentities([missing,sgp]));
var skinSnapshot = Json("{\"CanSelectSkin\":true,\"Skins\":[{\"ID\":103000,\"Name\":\"Classic\",\"ImagePath\":\"classic.png\",\"Enabled\":true},{\"ID\":103001,\"Name\":\"Owned\",\"Selected\":true,\"Enabled\":true},{\"ID\":103002,\"Name\":\"Chroma\",\"Selected\":false,\"Enabled\":true},{\"ID\":103003,\"Name\":\"Disabled\",\"Enabled\":false}]}");
var skins = MiniSkinData.Owned(skinSnapshot);
Check("Owned chroma retains its own action ID", skins[2].Id == 103002 && skins[2].Enabled);
Check("Selection reflects client-confirmed snapshot", skins.Single(s => s.Selected).Id == 103001);
Check("Disabled skin is not actionable", !skins[3].Enabled);
Check("Unavailable rows do not crash skin projection", MiniSkinData.Owned(Json("{\"CanSelectSkin\":true,\"Skins\":[{},null,{\"ID\":103000}]} ")).Length == 1);
Check("Read-only phase disables every skin action", MiniSkinData.Owned(Json(skinSnapshot.GetRawText().Replace("\"CanSelectSkin\":true","\"CanSelectSkin\":false"))).All(s => !s.Enabled));
Check("Skin grid grows from 3 to 6 columns", MiniSkinData.Columns(300) == 3 && MiniSkinData.Columns(600) == 6);
var requests = new List<(string Method,object?[] Args)>();
var state = Json("{\"availability\":{\"sgpServerId\":\"TENCENT_HN1\"},\"isTokenReady\":true,\"leagueServers\":{\"servers\":{\"TENCENT_HN1\":{\"matchHistory\":\"https://sgp\"},\"TENCENT_HN2\":{\"matchHistory\":\"https://sgp2\"}}}}");
var source = new PlayerDataSource((ns,method,args) => { requests.Add((method,args));return Task.FromResult(Json("{\"frames\":[]}")); }, (_,_) => Task.FromResult(state));
await source.ConfigureAsync("","lcu"); await source.TimelineAsync(123);
Check("LCU timeline routes to game-timelines endpoint", requests[^1].Method == "lcuRequest" && requests[^1].Args[1]?.ToString() == "/lol-match-history/v1/game-timelines/123");
await source.ConfigureAsync("","sgp"); await source.TimelineAsync(456);
Check("SGP timeline uses entitlements DETAILS", requests[^1].Method == "sgpRequest" && requests[^1].Args[1]?.ToString() == "entitlements" && requests[^1].Args[3]?.ToString() == "/match-history-query/v1/products/lol/@akari:sgpServerSubId@_456/DETAILS");
await source.ConfigureAsync("TENCENT_HN2","lcu"); await source.TimelineAsync(789);
Check("Cross-region timeline never uses local LCU", requests[^1].Method == "sgpRequest" && requests[^1].Args[0]?.ToString() == "TENCENT_HN2");
Check("Missing teammate kills keeps KP unknown", MatchDetailsData.KillParticipation(missing, [Participant("{}")] ) == null);
var notification = new FixtureNotifications("auto-accept,auto-matchmaking,respawn,update-progress", 120);
Check("Notification countdown uses backend epoch milliseconds", JsonSerializer.SerializeToElement(notification.Flow()).Number("willAcceptAt") > DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());
Check("Respawn scenario is alive until countdown expires", JsonSerializer.SerializeToElement(notification.Respawn()).Field("info").Boolean("isDead"));
Check("Update progress exposes real UI field names", JsonSerializer.SerializeToElement(notification.Update()).Field("updateProgressInfo").Number("downloadingProgress") == .65);
notification.Action("auto-gameflow-main", "cancelAutoAccept");
Check("Fixture cancel accept transitions state", !notification.WillAccept && notification.WillSearch);
notification.Action("auto-gameflow-main", "cancelAutoMatchmaking");
Check("Fixture cancel matchmaking transitions state", !notification.WillSearch);
notification.Action("self-update-main", "cancelUpdate");
Check("Fixture cancel update clears progress phase", JsonSerializer.SerializeToElement(notification.Update()).Field("updateProgressInfo").Text("phase") == "");
notification.Action("self-update-main", "startUpdate");
Check("Fixture retry update transitions to downloading", JsonSerializer.SerializeToElement(notification.Update()).Field("updateProgressInfo").Text("phase") == "downloading");
var timerPlatform = Json("{\"supportedGameModes\":[{\"gameMode\":\"KIWI\",\"abilityHaste\":70},{\"gameMode\":\"CLASSIC\",\"abilityHaste\":0}]}");
Check("Timer reads backend-supported haste", CDTimerData.AbilityHaste(timerPlatform,"KIWI") == 70);
Check("Unsupported modes do not synthesize a timer", CDTimerData.AbilityHaste(timerPlatform,"UNKNOWN") == null);
Check("KIWI flash cooldown uses 100/(100+haste)", CDTimerData.CountdownTarget(0,300,70) == 176470);
Check("Missing spell cooldown is not countdown zero", CDTimerData.CountdownTarget(0,null,70) == null);
Check("Native upward wheel decreases countdown", CDTimerData.Adjust("countdown",20000,120,false,0) == 14000);
Check("Reverse wheel increases countdown", CDTimerData.Adjust("countdown",20000,120,true,0) == 26000);
Check("Stopwatch cannot start in future", CDTimerData.Adjust("countup",20000,-120,false,21000) == 21000);
Check("Countdown cannot finish before now", CDTimerData.Adjust("countdown",20000,120,false,21000) == 21000);
Check("Elapsed timer renders OK", CDTimerData.Display("countdown",0,1) == "OK");
Check("Short timer retains tenth-second precision", CDTimerData.Display("countdown",9500,0) == "9.5");
Check("Long stopwatch caps at 999", CDTimerData.Display("countup",0,1000000) == "999");
var capturedLcuGame = Json(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"snapshots/lcu-game.json")));
var capturedLcuPlayers = MatchData.Participants(capturedLcuGame);
Check("Captured Tencent LCU game preserves ten identities", capturedLcuPlayers.Length == 10 && capturedLcuPlayers.All(p => p.Puuid.Length > 0));
Check("Captured LCU participant stats read numeric fields", capturedLcuPlayers.All(p => MatchDetailsData.Stat(p,"goldEarned").HasValue && MatchDetailsData.Stat(p,"kda").HasValue));
var capturedLcuTimeline = Json(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"snapshots/lcu-timeline.json")));
var capturedFrames = capturedLcuTimeline.Field("frames").Items().ToArray();
Check("Captured LCU timeline contains reported gold/XP", capturedFrames.Length > 0 && MatchDetailsData.TimelineMetric(capturedFrames[0],1,0).HasValue && MatchDetailsData.TimelineMetric(capturedFrames[0],1,2).HasValue);
Check("Captured LCU damage timeline is unavailable", capturedFrames.All(f => MatchDetailsData.TimelineMetric(f,1,3) == null));
var capturedSgp = Json(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"snapshots/sgp-summary.json")));
var capturedSgpPlayers = MatchData.Participants(capturedSgp.Field("games").Items().First());
Check("Captured Tencent SGP summary unwraps json payload", capturedSgpPlayers.Length == 10 && capturedSgpPlayers.All(p => MatchDetailsData.Stat(p,"goldEarned").HasValue));
var dialogQueue = new NativeDialogQueue();
var dialogRoot = new object(); var anotherRoot = new object();
var held = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
var firstStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
var first = dialogQueue.RunAsync(dialogRoot, async () => { firstStarted.SetResult(); return await held.Task; });
await firstStarted.Task;
bool secondStarted = false;
var second = dialogQueue.RunAsync(dialogRoot, () => { secondStarted = true; return Task.FromResult(2); });
Check("Same-root dialog waits while another is open", !secondStarted && !second.IsCompleted);
Check("Different-root dialog remains independent", await dialogQueue.RunAsync(anotherRoot, () => Task.FromResult(3)) == 3);
held.SetResult(1);
Check("First dialog returns its own result", await first == 1);
Check("Queued same-root dialog starts after prior close", await second == 2 && secondStarted);
Check("Released dialog can open nested callback dialog", await dialogQueue.RunAsync(dialogRoot, () => Task.FromResult(4)) == 4);
try { await dialogQueue.RunAsync<int>(dialogRoot, () => throw new InvalidOperationException("simulated ShowAsync failure")); } catch (InvalidOperationException) { }
Check("Throwing ShowAsync releases root slot", await dialogQueue.RunAsync(dialogRoot, () => Task.FromResult(5)) == 5);
var visibilityHeld = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
var visibilityBlocker = dialogQueue.RunAsync(dialogRoot, () => visibilityHeld.Task);
bool dialogVisible = true, hiddenDidShow = false;
var deferred = dialogQueue.RunAsync(dialogRoot, () => { hiddenDidShow = true; return Task.FromResult(6); }, () => dialogVisible);
dialogVisible = false; visibilityHeld.SetResult(0); await visibilityBlocker;
Check("Visibility is rechecked after acquiring queued slot", await deferred == null && !hiddenDidShow);
dialogVisible = true;
Check("Deferred dialog can retry when its window returns", await dialogQueue.RunAsync(dialogRoot, () => Task.FromResult(7), () => dialogVisible) == 7);
var multi = Participant("{\"puuid\":\"multikill\",\"doubleKills\":6,\"tripleKills\":4,\"quadraKills\":2,\"pentaKills\":1}");
var multiTags = HistoryCardData.Tags(Json("{\"mapId\":12,\"gameDuration\":900}"),multi,[multi]);
Check("Multikill tags subtract nested counts", multiTags.Single(t=>t.Key=="multiKill.penta").Count==1 && multiTags.Single(t=>t.Key=="multiKill.quadra").Count==1 && multiTags.Single(t=>t.Key=="multiKill.triple").Count==2 && multiTags.Single(t=>t.Key=="multiKill.double").Count==2);
Check("Penta wins original tag priority", multiTags[0].Key=="multiKill.penta");
var damageLeader = Participant("{\"puuid\":\"leader\",\"totalDamageDealtToChampions\":12000,\"goldEarned\":6000,\"damageDealtToTurrets\":1000,\"challenges\":{\"soloKills\":3}}");
var nonLeader = Participant("{\"puuid\":\"other\",\"totalDamageDealtToChampions\":1000,\"goldEarned\":7000,\"damageDealtToTurrets\":100}");
var leaderTags = HistoryCardData.Tags(Json("{}"),damageLeader,[damageLeader,nonLeader]);
Check("Global damage leader gets best tag", leaderTags.Any(t=>t.Key=="damage.best")&&!leaderTags.Any(t=>t.Key=="damage.team"));
Check("Turret damage uses canonical alias", leaderTags.Any(t=>t.Key=="tower.best"));
Check("SGP challenge yields solo tag",leaderTags.Any(t=>t.Key=="solo"&&t.Count==3));
Check("Incomplete challenge values never create tags", !HistoryCardData.Tags(Json("{}"),missing,[missing]).Any(t=>t.Key=="solo"));
var mutatorResources=Json("{\"maps\":{\"12\":{\"name\":\"Howling Abyss\"}},\"gameModeMutators\":{\"12\":{\"MapNameBase\":\"Abyss\",\"Mutators\":[{\"Mutator\":{\"ExpandedMutator\":\"kiwi\"},\"MapNameOverride\":\"Mayhem map\"}]}}}");
Check("Map mutator selects original override",HistoryCardData.MapName(mutatorResources,Json("{\"mapId\":12,\"gameModeMutators\":[\"KIWI\"]}"))=="Mayhem map");
Check("Map missing mutator uses base name",HistoryCardData.MapName(mutatorResources,Json("{\"mapId\":12}"))=="Abyss");
Check("Arena placement marks champion crown",HistoryCardData.IsChampion(Participant("{\"subteamPlacement\":1}")));
var replayCalls = new List<(string Method,string Path,JsonElement Body)>();
var replayService = new ReplayService((ns,method,args)=>{replayCalls.Add((args[0]?.ToString()??"",args[1]?.ToString()??"",JsonSerializer.SerializeToElement(args[2])));return Task.FromResult(args[1]?.ToString()=="/lol-replays/v1/configuration"?Json("{\"isReplaysEnabled\":true,\"gameVersion\":\"current\"}"):Json("{\"state\":\"download\"}"));});
var replayGame=Json("{\"gameId\":77,\"gameVersion\":\"recorded\",\"gameType\":\"MATCHED_GAME\",\"queueId\":2400,\"gameCreation\":1000,\"gameDuration\":10,\"gameEndTimestamp\":50000}");
await replayService.InitializeAsync(replayGame,"lcu");
Check("LCU replay create uses current config version and derived end",replayCalls[1].Path=="/lol-replays/v2/metadata/77/create"&&replayCalls[1].Body.Text("gameVersion")=="current"&&replayCalls[1].Body.Number("gameEnd")==11000);
replayCalls.Clear();await replayService.InitializeAsync(replayGame,"sgp");
Check("SGP replay create preserves original version and end",replayCalls[1].Body.Text("gameVersion")=="recorded"&&replayCalls[1].Body.Number("gameEnd")==50000);
await replayService.ExecuteAsync(77,"watch");
Check("Replay watch sends upstream component type",replayCalls[^1].Method=="POST"&&replayCalls[^1].Path=="/lol-replays/v1/rofls/77/watch"&&replayCalls[^1].Body.Text("componentType")=="replay-button_match-history");
try{await replayService.ExecuteAsync(77,"incompatible");Check("Incompatible replay cannot execute",false);}catch(InvalidOperationException){passed++;}
Check("Perkstyles resolve nested styles catalog",HistoryCardData.Resource(Json("{\"perkstyles\":{\"styles\":{\"8100\":{\"name\":\"Domination\"}}}}"),"perkstyles",8100).Text("name")=="Domination");
Check("Augment resolves real small icon field",HistoryCardData.IconPath(Json("{\"augmentSmallIconPath\":\"augment.png\"}"))=="augment.png");
Check("Long match duration includes hours",HistoryCardData.Duration(3700)=="01:01:40");
int disabledReplayRequests = 0;
var disabledReplay = new ReplayService((ns,method,args)=>{disabledReplayRequests++;return Task.FromResult(Json("{\"isReplaysEnabled\":false}"));});
var disabledMetadata = await disabledReplay.InitializeAsync(replayGame,"lcu");
Check("Disabled replay configuration hides button without create requests", disabledMetadata.ValueKind==JsonValueKind.Undefined&&disabledReplayRequests==1);
var tagCalls = new List<(string Namespace,string Method,JsonElement[] Arguments)>();
var tagActions = new OngoingPlayerActions((ns,method,args) => { tagCalls.Add((ns,method,args.Select(a=>JsonSerializer.SerializeToElement(a)).ToArray())); return Task.FromResult(Json("[{\"markedBySelf\":false,\"tag\":\"other\"},{\"markedBySelf\":true,\"tag\":\"current\"}]")); });
Check("Ongoing tag loads current user's tag from backend",await tagActions.LoadTagAsync("target","me")=="current"&&tagCalls[0].Method=="getPlayerTags"&&tagCalls[0].Arguments[0].Text("selfPuuid")=="me");
tagCalls.Clear(); await tagActions.SaveTagAsync("target","me","  preserve spaces  ",Json("{\"region\":\"TENCENT\",\"rsoPlatformId\":\"HN10\"}"));
Check("Tag save preserves entered text and current auth",tagCalls[0].Arguments[0].Text("tag")=="  preserve spaces  "&&tagCalls[0].Arguments[0].Text("rsoPlatformId")=="HN10");
Check("Tag save reloads only saved info after successful write",tagCalls[1].Namespace=="ongoing-game-main"&&tagCalls[1].Method=="reloadPlayer"&&tagCalls[1].Arguments[1].Field("includes").Items().Single().GetString()=="savedInfo");
tagCalls.Clear(); await tagActions.SaveTagAsync("target","me"," \t ",Json("{}"));
Check("Whitespace tag deletes via null without auth fields",tagCalls[0].Arguments[0].Field("tag").ValueKind==JsonValueKind.Null&&tagCalls[0].Arguments[0].Field("region").ValueKind==JsonValueKind.Undefined);
bool reloadAfterFailure=false;
var failedTag=new OngoingPlayerActions((ns,method,args)=>{if(method=="reloadPlayer")reloadAfterFailure=true;throw new InvalidOperationException("save failed");});
try{await failedTag.SaveTagAsync("target","me","tag",Json("{}"));Check("Tag failure is retained for UI retry",false);}catch(InvalidOperationException){Check("Failed tag write does not reload stale cache",!reloadAfterFailure);}
var arenaDraft=JsonSerializer.SerializeToElement(MatchDetailsData.CreateDraft(Json("{\"gameMode\":\"CHERRY\",\"queueId\":1700,\"participants\":[{\"puuid\":\"p1\",\"teamId\":100,\"championId\":103},{\"puuid\":\"p2\",\"teamId\":200,\"championId\":147}]}"),"absent"));
Check("Arena simulation merges original TEAM-ALL roster",arenaDraft.Field("teams").Field("TEAM-ALL").Items().Count()==2&&arenaDraft.Field("teams").EnumerateObject().Count()==1);
Check("Simulation omits missing owner and unreported positions",arenaDraft.Field("puuid").ValueKind==JsonValueKind.Null&&arenaDraft.Field("positions").ValueKind==JsonValueKind.Null);
var normalDraft=JsonSerializer.SerializeToElement(MatchDetailsData.CreateDraft(Json("{\"gameMode\":\"CLASSIC\",\"participants\":[{\"puuid\":\"p1\",\"teamId\":100,\"championId\":103,\"teamPosition\":\"MIDDLE\"},{\"puuid\":\"p2\",\"teamId\":200,\"championId\":147}]}"),"p1"));
Check("Simulation keeps focused participant and reported position only",normalDraft.Text("puuid")=="p1"&&normalDraft.Field("positions").EnumerateObject().Count()==1&&normalDraft.Field("positions").Field("p1").Text("selected")=="MIDDLE");
Check("Ongoing selected SGP queue preserves literal tag and AND",JsonSerializer.SerializeToElement(OngoingPlayerActions.QueryParameters("q_2403")).Text("tag")=="q_2403"&&JsonSerializer.SerializeToElement(OngoingPlayerActions.QueryParameters("q_2403")).Text("tagsQueryType")=="AND");
Check("Ongoing all-tag clears query parameters",!JsonSerializer.SerializeToElement(OngoingPlayerActions.QueryParameters("<akari:all>")).EnumerateObject().Any());
object RuneStyle(int id,int[] allowed,int offset)=>new{id,name="Style"+id,allowedSubStyles=allowed,slots=new[]{new{type="kKeyStone",perks=new[]{offset+1,offset+2}},new{type="kMixedRegularSplashable",perks=new[]{offset+3,offset+4}},new{type="kMixedRegularSplashable",perks=new[]{offset+5,offset+6}},new{type="kMixedRegularSplashable",perks=new[]{offset+7,offset+8}},new{type="kStatMod",perks=new[]{5005,5008}},new{type="kStatMod",perks=new[]{5008,5002}},new{type="kStatMod",perks=new[]{5002,5001}}}};
var runeCatalog=JsonSerializer.SerializeToElement(new{schemaVersion=2,styles=new Dictionary<string,object>{{"8000",RuneStyle(8000,[8100],100)},{"8100",RuneStyle(8100,[8000],200)}}});
var savedRune=new RuneConfig(8000,8100,[101,103,105,107,203,205,5005,5008,5002]);
var championDraft=new ChampionConfigDraft(runeCatalog,savedRune,new SpellConfig(4,14));
Check("Champion storage keys preserve ranked-position and mode-only",ChampionConfigDraft.StorageKey("ranked","middle")=="ranked-middle"&&ChampionConfigDraft.StorageKey("aram","middle")=="aram");
Check("Saved complete rune satisfies actual catalog slots",championDraft.ValidRunes()&&!championDraft.RunesChanged);
championDraft.SelectPrimaryPerk(1,104);championDraft.SelectPrimary(8100);
Check("Primary style change preserves unsaved rune selections",championDraft.Runes!.SelectedPerkIds[1]==104&&championDraft.Runes.SubStyleId==8000);
championDraft.RestoreRunes();Check("Restore rune recovers saved copy",!championDraft.RunesChanged&&championDraft.Runes!.SelectedPerkIds[1]==103);
championDraft.ClearRunes();Check("Clear rune is a local null draft until save",championDraft.RunesChanged&&championDraft.RunePayload==null);championDraft.RestoreRunes();
Check("Cleared rune can be restored before writing",!championDraft.RunesChanged);
championDraft.SelectSecondary(8000);Check("Same-style secondary selection rejected",championDraft.Runes!.SubStyleId==8100);
championDraft.SelectSecondaryPerk(0,204);championDraft.SelectSecondaryPerk(2,207);
Check("Third secondary row replaces oldest and remains sorted",championDraft.Runes!.SelectedPerkIds[4]==204&&championDraft.Runes.SelectedPerkIds[5]==207&&championDraft.ValidRunes());
championDraft.SelectPrimaryPerk(1,101);Check("Wrong-row rune cannot enter primary selection",championDraft.Runes!.SelectedPerkIds[1]==103);
var oldSchema=new ChampionConfigDraft(Json("{\"schemaVersion\":1}"),savedRune,null);Check("Unsupported rune schema cannot save a page",!oldSchema.ValidRunes());
championDraft.SelectSpell(true,14,[4,14]);Check("Choosing other slot's spell swaps distinct slots",championDraft.Spells==new SpellConfig(14,4));
championDraft.ClearSpells();Check("Clear spell stages null without losing restore baseline",championDraft.SpellsChanged&&championDraft.SpellPayload==null);championDraft.RestoreSpells();Check("Restore spell returns saved ids",!championDraft.SpellsChanged);
var runePayload=JsonSerializer.SerializeToElement(championDraft.RunePayload);Check("Rune save payload preserves upstream lowercase field names",runePayload.Field("primaryStyleId").ValueKind==JsonValueKind.Number&&runePayload.Field("selectedPerkIds").Items().Count()==9);
var autoGroups=AutoSelectData.Groups(Json("{\"groups\":[{\"groupId\":\"custom-server-mode\",\"positions\":[\"default\"],\"additionalPicks\":[-3],\"excludedPicks\":[-1],\"additionalBans\":[],\"excludedBans\":[]},{\"groupId\":\"ranked\",\"positions\":[\"top\",\"jungle\",\"middle\",\"bottom\",\"utility\"]}]}"));
Check("Auto select groups preserve backend custom ids and positions",autoGroups[0].Id=="custom-server-mode"&&autoGroups[1].Positions.Length==5&&!autoGroups[1].Positions.Contains("default"));
var autoChampions=AutoSelectData.Champions(Json("{\"103\":{\"name\":\"九尾妖狐\"},\"147\":{\"id\":147,\"name\":\"星籁歌姬\"}}"),Json("{\"heroListMap\":{\"103\":{\"keywords\":\"阿狸,ahri\"}}}"));
Check("Champion catalog retains keyed identities and extra aliases",autoChampions[0].Id==103&&autoChampions[0].Keywords.Contains("ahri"));
var autoPicks=AutoSelectData.Candidates(autoChampions,autoGroups[0],false,new HashSet<int>{147},"none","bravery");
Check("Pick candidates include permitted bravery and exclude dummy/disabled",autoPicks.Select(c=>c.Id).SequenceEqual(new[]{-3,103}));
var autoBans=AutoSelectData.Candidates(autoChampions,autoGroups[0],true,new HashSet<int>(),"none","bravery");
Check("Ban candidates allow no-ban without adding pick-only bravery",autoBans.Any(c=>c.Id==-1)&&autoBans.All(c=>c.Id!=-3));
Check("Exact backend mode-position path is preserved",AutoSelectData.Path(true,"custom-server-mode","default")=="banConfig.custom-server-mode.champions.default");
Check("Champion addition deduplicates while preserving order",AutoSelectData.Add([103,-3,103],147).SequenceEqual(new[]{103,-3,147}));
Check("Ordered champion move retains special ids",AutoSelectData.Move([103,-3,147],-3,-1).SequenceEqual(new[]{-3,103,147}));
Check("Champion move at boundary is no-op",AutoSelectData.Move([103,147],103,-1).SequenceEqual(new[]{103,147}));
Check("Drag reorder follows original target index",AutoSelectData.Drop([103,147,-3],103,-3).SequenceEqual(new[]{147,-3,103}));
Check("Remove champion leaves remaining priority",AutoSelectData.Remove([103,-1,147],-1).SequenceEqual(new[]{103,147}));
var autoPositions=Json("{\"103\":{\"recommendedPositions\":[\"MIDDLE\"]},\"147\":{\"recommendedPositions\":[\"UTILITY\"]}}");
Check("Champion search supports original aliases and ids",AutoSelectData.Matches(autoChampions[0],"ahri",null,autoPositions)&&AutoSelectData.Matches(autoChampions[0],"103",null,autoPositions));
Check("Position filter uses real LCU recommendations",AutoSelectData.Matches(autoChampions[0],"","MIDDLE",autoPositions)&&!AutoSelectData.Matches(autoChampions[0],"","UTILITY",autoPositions));
Check("Unavailable recommended positions leave search usable",AutoSelectData.Matches(autoChampions[0],"", "JUNGLE",autoPositions)&&AutoSelectData.Matches(autoChampions[0],"", "MIDDLE",default));
Check("Champion search follows subsequence matching",AutoSelectData.Matches(autoChampions[0],"九狐",null,default));
var actualHeroList=AutoSelectData.Champions(Json("{\"103\":{\"name\":\"九尾妖狐\"}}"),Json("{\"heroList\":{\"hero\":[{\"heroId\":\"103\",\"keywords\":\"狐狸,ahri,ali\"}]}}"));
Check("Champion aliases read actual gtimg heroList envelope",AutoSelectData.Matches(actualHeroList[0],"ali",null,default));
using (var pinyinOracle=JsonDocument.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"pinyin-oracle.json"))))
{
    int converted=0;
    foreach(var row in pinyinOracle.RootElement.GetProperty("transliterations").EnumerateArray())
    {
        string input=row[0].GetString()!,expected=row[1].GetString()!,actual=NativePinyin.Convert(input);
        if(actual!=expected) throw new InvalidOperationException($"Original pinyin-pro conversion mismatch: {input}: expected {expected}, actual {actual}");
        converted++;
    }
    Check($"Native default conversion matches pinyin-pro 3.28.1 oracle ({converted} inputs)",converted>30000);
    int matched=0;
    foreach(var row in pinyinOracle.RootElement.GetProperty("matches").EnumerateArray())
    {
        string pattern=row[0].GetString()!,title=row[1].GetString()!;
        if(NativePinyin.Matches(pattern,title)!=row[2].GetBoolean())throw new InvalidOperationException($"Original champion matcher mismatch: {pattern} / {title}");
        matched++;
    }
    Check($"Native matching preserves original three-stage subsequence semantics ({matched} pairs)",matched>100);
}
Check("Full pinyin works without any GTIMG aliases",AutoSelectData.Matches(new(147,"星籁歌姬",""),"xinglaigeji",null,default));
Check("Initials are a subsequence of full pinyin",AutoSelectData.Matches(new(147,"星籁歌姬",""),"XLGJ",null,default));
Check("Chinese search pattern is transliterated too",AutoSelectData.Matches(new(103,"阿狸",""),"阿里",null,default));
Check("Polyphonic phrase overrides per-character reading",NativePinyin.Convert("重庆银行音乐")=="chongqingyinhangyinyue");
Check("Original pinyin ü does not silently normalize to v or u",NativePinyin.Matches("nü","女警")&&!NativePinyin.Matches("nv","女警"));
Check("Empty title cannot match empty search",!NativePinyin.Matches("",""));
Check("Search whitespace retains upstream meaning",!NativePinyin.Matches(" ","星籁歌姬"));
Check("Pinyin match still respects LCU position filter",!AutoSelectData.Matches(new(103,"阿狸",""),"ali","UTILITY",autoPositions));
var miniSnapshot=Json("{\"Connected\":true,\"Phase\":\"ChampSelect\",\"ChampionID\":103,\"CanSelectSkin\":true,\"Skins\":[{\"ID\":103001,\"Name\":\"Owned\",\"Enabled\":true,\"Selected\":true},{\"ID\":103002,\"Name\":\"Chroma\",\"Enabled\":true}]} ");
var miniInteraction=new MiniInteractionState(); miniInteraction.Observe(miniSnapshot);
long miniRequest=miniInteraction.Begin("skin",103002);
Check("Mini pending skin displays intent without selecting it",miniInteraction.SkinStatus(miniSnapshot,true)=="Applying: Chroma"&&MiniSkinData.Owned(miniSnapshot).Single(s=>s.Selected).Id==103001);
miniInteraction.Complete(miniRequest,"request failed"); miniInteraction.Observe(miniSnapshot);
Check("Mini local action error survives empty backend error refresh",miniInteraction.DisplayError(miniSnapshot)=="request failed"&&miniInteraction.SkinStatus(miniSnapshot,true).Contains("failed"));
long retriedSkin=miniInteraction.Begin("skin",103002);miniInteraction.Complete(retriedSkin,"");
Check("Successful skin request still waits for client-selected skin",miniInteraction.SkinStatus(miniSnapshot,true)=="Selected: Owned");
long oldMiniRequest=miniInteraction.Begin("skin",103002);miniInteraction.Observe(Json(miniSnapshot.GetRawText().Replace("\"ChampionID\":103","\"ChampionID\":147")));miniInteraction.Complete(oldMiniRequest,"old hero failed");
Check("Old champion request completion cannot replace new hero feedback",miniInteraction.Error==""&&!miniInteraction.SkinFailed&&miniInteraction.PendingKind=="");
var staleMiniError=Json(miniSnapshot.GetRawText().TrimEnd().TrimEnd('}')+",\"Error\":\"old request failed\"}");miniInteraction.Observe(staleMiniError);long miniRetry=miniInteraction.Begin("champion",147);miniInteraction.Complete(miniRetry,"");
Check("Successful retry dismisses stale backend error",miniInteraction.DisplayError(staleMiniError)=="");
Check("Backend skin load failure is distinct from empty owned list",new MiniInteractionState().SkinStatus(Json("{\"SkinsLoadFailed\":true}"),true)=="Unable to load owned skins");
Check("Disabled skin selection explains unavailable state",new MiniInteractionState().SkinStatus(Json(miniSnapshot.GetRawText().Replace("\"CanSelectSkin\":true","\"CanSelectSkin\":false")),true).Contains("unavailable"));
Check("Backend pending chroma is presented without optimistic selection",new MiniInteractionState().SkinStatus(Json("{\"PendingSkinID\":103002,\"PendingSkinName\":\"Owned chroma\"}"),true)=="Applying: Owned chroma");
var miniEnvelope=Json("{\"state\":{\"champSelect\":{\"session\":{\"allowRerolling\":true,\"timer\":{\"phase\":\"FINALIZATION\"}}},\"gameflow\":{\"session\":{\"gameData\":{\"queue\":{\"id\":450}},\"map\":{\"id\":12}}}}}");
Check("Zero reroll count still renders disabled original reroll controls",MiniViewData.ShowReroll(Json("{\"Rerolls\":0}"),miniEnvelope));
Check("Subset selection with no rerolls does not show reroll controls",!MiniViewData.ShowReroll(Json("{\"Rerolls\":0}"),Json(miniEnvelope.GetRawText().Replace("\"allowRerolling\":true","\"allowRerolling\":true,\"allowSubsetChampionPicks\":true"))));
Check("Backend explicit reroll visibility takes precedence",!MiniViewData.ShowReroll(Json("{\"ShowReroll\":false,\"Rerolls\":2}"),miniEnvelope));
string miniSignature=MiniViewData.SelectionSignature(miniSnapshot,miniEnvelope,false,"light");
Check("Same-phase queue changes invalidate Mini selection view",miniSignature!=MiniViewData.SelectionSignature(miniSnapshot,Json(miniEnvelope.GetRawText().Replace("450","2400")),false,"light"));
Check("Spectator transition invalidates Mini selection view",miniSignature!=MiniViewData.SelectionSignature(miniSnapshot,Json(miniEnvelope.GetRawText().Replace("\"allowRerolling\":true","\"allowRerolling\":true,\"isSpectating\":true")),false,"light"));
Check("Countdown-only automation update preserves skin virtualization",miniSignature==MiniViewData.SelectionSignature(miniSnapshot,Json(miniEnvelope.GetRawText()[..^1]+",\"automation\":{\"countdown\":123}}"),false,"light"));
Check("Theme changes refresh native Mini balance contrast",miniSignature!=MiniViewData.SelectionSignature(miniSnapshot,miniEnvelope,false,"dark"));
var damagePlayer = Participant("{\"totalDamageDealtToChampions\":100,\"physicalDamageDealtToChampions\":20,\"magicDamageDealtToChampions\":60,\"trueDamageDealtToChampions\":20,\"totalDamageTaken\":200,\"physicalDamageTaken\":150,\"magicalDamageTaken\":50,\"trueDamageTaken\":0}");
var damageOpponent = Participant("{\"totalDamageDealtToChampions\":400,\"totalDamageTaken\":800}") with { TeamId = 200, TeamKey = "TEAM-200" };
var damage = MatchTeamData.Damage(damagePlayer, [damagePlayer, damageOpponent], false);
Check("Damage bars compare both teams against match maximum", damage.Baseline == 400 && damage.BaselineRatio == .25);
Check("Damage breakdown shares use player total instead of match maximum", damage.Share(damage.Magic) == .6 && damage.Share(damage.True) == .2);
var taken = MatchTeamData.Damage(damagePlayer, [damagePlayer, damageOpponent], true);
Check("Damage taken uses independent match-wide maximum", taken.Baseline == 800 && taken.BaselineRatio == .25);
Check("LCU magicalDamageTaken alias populates magic segment", taken.Magic == 50);
Check("Known zero damage segment has zero percent", taken.Share(taken.True) == 0);
var unavailableDamage = MatchTeamData.Damage(missing, [missing], false);
Check("Unreported damage has no numeric percentage", unavailableDamage.Total == null && unavailableDamage.BaselineRatio == null && unavailableDamage.Share(0) == null);
Check("Reported zero damage has finite percentage", new MatchDamage(0, 0, 0, 0, 0).BaselineRatio == 0);
Check("Missing damage subtype stays unknown", MatchTeamData.Damage(damageOpponent, [damageOpponent], false).Physical == null);
Check("Unknown teammate does not hide observed damage baseline", MatchTeamData.Damage(damagePlayer, [damagePlayer, missing], false).Baseline == 100);
Check("Zero duration cannot invent a per-minute stat", MatchTeamData.PerMinute(100, 0) == null);
Check("Missing CS cannot invent CS per minute", MatchTeamData.PerMinute(null, 600) == null);
Check("Per-minute rate uses seconds from the match", MatchTeamData.PerMinute(100, 600) == 10);
Check("Modern reported zero objectives win over legacy count", MatchTeamData.Objective(Json("{\"objectives\":{\"tower\":{\"kills\":0}},\"towerKills\":7}"), "tower", "towerKills") == 0);
Check("Legacy LCU team objectives are retained", MatchTeamData.Objective(Json("{\"towerKills\":7}"), "tower", "towerKills") == 7);
Check("Missing objectives do not create zero objective badges", MatchTeamData.Objective(Json("{}"), "horde", "") == null);
Check("Sixth augment expands slots for all teammates", MatchTeamData.AugmentSlots([Participant("{\"playerAugment6\":10}"), missing]) == 6 && MatchTeamData.AugmentSlots([missing]) == 5);
Check("Empty and bot identities cannot navigate", !MatchTeamData.CanOpenPlayer(missing with { Puuid = "" }, false) && !MatchTeamData.CanOpenPlayer(missing with { Puuid = "00000000-0000-0000-0000-000000000000" }, false));
Check("Streamer mode disables player navigation", !MatchTeamData.CanOpenPlayer(sgp, true) && MatchTeamData.CanOpenPlayer(sgp, false));
var radarSelf = Participant("{\"kills\":1,\"deaths\":10,\"assists\":2,\"totalDamageDealtToChampions\":2,\"totalDamageTaken\":8,\"goldEarned\":50,\"totalMinionsKilled\":3,\"neutralMinionsKilled\":2,\"totalHeal\":0}");
var radarTeam = Participant("{\"kills\":3,\"deaths\":2,\"assists\":1,\"totalDamageDealtToChampions\":6,\"totalDamageTaken\":12,\"goldEarned\":150,\"totalMinionsKilled\":10,\"neutralMinionsKilled\":0,\"totalHeal\":2}");
var radarOther = Participant("{\"kills\":1,\"deaths\":1,\"assists\":1,\"totalDamageDealtToChampions\":10,\"totalDamageTaken\":20,\"goldEarned\":100,\"totalMinionsKilled\":20,\"neutralMinionsKilled\":0,\"totalHeal\":1}") with { TeamId = 200, TeamKey = "TEAM-200" };
var radar = MatchRadarData.Metrics(radarSelf, [radarSelf, radarTeam, radarOther]);
Check("Radar keeps original seven metric order", string.Join(",", radar.Select(m => m.Key)) == "totalDamageDealtToChampions,totalDamageTaken,goldEarned,cs,kda,killParticipation,totalHeal");
Check("Radar uses actual maximum below one rather than clamping baseline", MatchRadarData.Metrics(radarSelf, [radarSelf])[4].PlayerRatio == 1);
Check("Radar damage compares both teams", radar[0].Value == 2 && radar[0].PlayerRatio == .2);
Check("Radar team average excludes opponents", radar[0].TeamRatio == .4 && radar[1].TeamRatio == .5);
Check("Radar CS uses lane and jungle", radar[3].Value == 5 && radar[3].PlayerRatio == .25);
Check("Radar KDA uses original zero-death divisor", radar[4].Value == .3 && radar[4].TeamRatio == .575);
Check("Radar KP uses respective team kills for match-wide maximum", radar[5].Value == .75 && radar[5].PlayerRatio == .375 && radar[5].TeamRatio == .4375);
Check("Radar reported zero healing remains zero", radar[6].Value == 0 && radar[6].PlayerRatio == 0);
var incompleteRadar = MatchRadarData.Metrics(radarSelf, [radarSelf, missing]);
Check("Radar unknown teammate does not fabricate team average", incompleteRadar[0].TeamRatio == null && incompleteRadar[0].PlayerRatio == 1);
Check("Radar all-missing metric stays unknown", MatchRadarData.Metrics(missing, [missing])[0].PlayerRatio == null);
Check("Radar all-zero metric is finite zero", MatchRadarData.Metrics(radarSelf, [radarSelf])[6].PlayerRatio == 0);
Check("Timeline preserves genuine empty frame array", MatchDetailsData.Timeline(Json("{\"json\":{\"frames\":[]}}")).Field("frames").ValueKind == JsonValueKind.Array);
foreach (var invalidTimeline in new[] { "{}", "{\"json\":{\"frames\":{}}}", "{\"error\":\"AccessDenied\"}" })
    try { MatchDetailsData.Timeline(Json(invalidTimeline)); Check("Timeline rejects malformed response", false); } catch (InvalidOperationException) { passed++; }
Console.WriteLine($"Native data business contracts: {passed} passed");

namespace LeagueAkari.WinUI.Services
{
    public sealed class BackendClient
    {
        public Task<JsonElement> CallAsync(string ns,string method,params object?[] args) => throw new NotSupportedException();
        public Task<JsonElement> StateAsync(string ns,string state) => throw new NotSupportedException();
    }
}
