using System.Text.Json;
using LeagueAkari.WinUI.Services;
int passed=0;
void Equal<T>(T expected,T actual,string message){passed++;if(!EqualityComparer<T>.Default.Equals(expected,actual))throw new Exception(message+": "+actual);}
JsonElement Json(string value)=>JsonDocument.Parse(value).RootElement.Clone();
var state=Json("""{"auth":{"pid":10},"connectingClient":{"pid":20}}""");
var ux=Json("""{"launchedClients":[{"pid":10,"region":"TENCENT","rsoPlatformId":"HN1"},{"pid":20,"region":"TENCENT","rsoPlatformId":"HN10"},{"pid":20,"region":"TENCENT","rsoPlatformId":"HN10"},{"pid":30,"region":"NA"},{"pid":0}]}""");
var clients=ConnectionData.OtherClients(state,ux);Equal("20,30",string.Join(',',clients.Select(client=>client.Pid)),"Connected PID excluded; duplicate/invalid discoveries excluded");Equal(20,ConnectionData.ConnectingPid(state),"In-flight target retained");Equal(20,ConnectionData.Choose(clients,30,20)?.Pid,"Connecting client is selected over previous client");Equal(30,ConnectionData.Choose(clients,30,0)?.Pid,"Previous valid selection preserved");Equal(20,ConnectionData.Choose(clients,99,0)?.Pid,"Closed selection falls back to discovered client");Equal<ConnectionClient?>(null,ConnectionData.Choose([],20,0),"No fake client when none available");
Equal("10,20,30",string.Join(',',ConnectionData.OtherClients(Json("{}"),ux).Select(client=>client.Pid)),"Disconnected shows all discovered clients");Equal("TENCENT_HN10",ConnectionData.ServerId("tencent","hn10"),"Tencent platform normalized");Equal("NA1",ConnectionData.ServerId("na",""),"LCU NA alias");Equal("LA1",ConnectionData.ServerId("lan",""),"LCU Latin north alias");Equal("OC1",ConnectionData.ServerId("oce",""),"LCU Oceania alias");Equal("EUW",ConnectionData.ServerId("EUW1",""),"LCU Europe alias");
var sgp=Json("""{"leagueServers":{"serverNames":{"zh-CN":{"TENCENT_HN10":"黑色玫瑰"},"en":{"TENCENT_HN10":"Black Rose"}}}}""");Equal("黑色玫瑰",ConnectionData.ServerName(sgp,"TENCENT","HN10","zh-CN"),"Actual locale server name");Equal("Black Rose",ConnectionData.ServerName(sgp,"TENCENT","HN10","en"),"Server locale changes");Equal("NA1",ConnectionData.ServerName(sgp,"NA","","en"),"Missing map falls back to SGP ID");
foreach(string phase in new[]{"WaitingForStats","PreEndOfGame","EndOfGame"})Equal(true,ConnectionData.IsEndgame(phase),"Original playAgain phase "+phase);foreach(string phase in new[]{"InProgress","ChampSelect","Reconnect","None"})Equal(false,ConnectionData.IsEndgame(phase),"PlayAgain hidden "+phase);
var now=DateTimeOffset.UtcNow;Equal(true,ConnectionData.ShouldPeek(null,now),"New discovery peek immediately");Equal(false,ConnectionData.ShouldPeek(now.AddSeconds(-9),now),"Repeated connection events do not repoll within10s");Equal(true,ConnectionData.ShouldPeek(now.AddSeconds(-10),now),"Original10s profile discovery refresh");
Console.WriteLine($"Connection discovery and selection contracts: {passed} passed");
