using System.Text.Json;
using LeagueAkari.WinUI.Services;

int passed = 0;
void Check(string name, bool value) { if (!value) throw new Exception(name); ++passed; Console.WriteLine("PASS " + name); }
JsonElement J(object value) => JsonSerializer.SerializeToElement(value);
var position = OngoingCardData.Position(J(new { position = "BOTTOM", role = new { assignmentReason = "AUTOFILL", primary = "MIDDLE", secondary = "UNSELECTED" } }), J(new { positions = new { MIDDLE = 8, TOP = 5, BOTTOM = 2, NONE = 12, UTILITY = 0 } }))!;
Check("Assigned position retained", position.Current == "BOTTOM");
Check("Autofill and requested roles retained", position.Reason == "AUTOFILL" && position.Primary == "MIDDLE" && position.Secondary == "UNSELECTED");
Check("Recent positions descending and exclude none/zero", position.Recent.SequenceEqual(new[] { "MIDDLE", "TOP", "BOTTOM" }));
Check("No current position hides role panel", OngoingCardData.Position(J(new { position = "NONE" }), default) == null);
Check("Unavailable role does not invent reason", OngoingCardData.Position(J(new { position = "TOP" }), default) is { Reason: "", Recent.Length: 0 });
var analysis = J(new { winLoss = new { all = new { count = 20, winRate = .25 }, cherry = new { count = 4, winRate = .75, top1Rate = .5 } } });
Check("Normal statistics use all queues", OngoingCardData.Wins("KIWI", analysis, [], "self") is { Count: 20, Rate: .25, Top1Rate: null });
Check("Cherry statistics use cherry-only count and top1", OngoingCardData.Wins("CHERRY", analysis, [], "self") is { Count: 4, Rate: .75, Top1Rate: .5 });
Check("No cherry history yields actual zero", OngoingCardData.Wins("CHERRY", default, [], "self") is { Count: 0, Rate: 0, Top1Rate: 0 });
var values = new Dictionary<string, double> { ["a"] = 1, ["b"] = 2, ["c"] = 2, ["d"] = 2, ["e"] = 3 };
var outliers = OngoingCardData.KdaOutliers(values);
Check("Original .65 IQR below", outliers["a"] == "below");
Check("Original .65 IQR above", outliers["e"] == "over");
Check("IQR exact bound retained", !outliers.ContainsKey("c"));
Check("Fewer than five players never flagged", OngoingCardData.KdaOutliers(values.Take(4).ToDictionary()).Count == 0);
Check("Team KDA divides summed K/A by summed deaths, not average player KDA", OngoingCardData.TeamKda([new() { Kills = 10, Deaths = 1, Kda = 10 }, new() { Kills = 0, Deaths = 9, Kda = 0 }]) == 1);
Check("Team zero deaths uses original noZero", OngoingCardData.TeamKda([new() { Kills = 2, Assists = 3 }]) == 5);
JsonElement Game(long id, bool opponent = false, bool cherry = false, bool missing = false) => J(new { gameId = id, gameType = "MATCHED_GAME", queueId = cherry ? 1700 : 2400, gameMode = cherry ? "CHERRY" : "ARAM", gameCreation = 1700000000000 + id * 1000, participants = new[] { new { participantId = 1, puuid = "self", teamId = 100, championId = 1, kills = 1, deaths = 2, assists = 3, win = true, playerSubteamId = 1, subteamPlacement = 1 }, new { participantId = 2, puuid = missing ? "missing" : "target", teamId = opponent ? 200 : 100, championId = 2, kills = 4, deaths = 5, assists = 6, win = !opponent, playerSubteamId = cherry ? 2 : 1, subteamPlacement = 2 } } });
JsonElement Hist(params JsonElement[] games) => J(new Dictionary<string, object> { ["self"] = new { data = games }, ["target"] = new { data = games } });
JsonElement Saved(params long[] ids) => J(new { encounteredGames = new { data = ids.Select(id => new { id, gameId = id, selfPuuid = "self", puuid = "target", queueType = "KIWI", updateAt = "2026-10-07T01:00:00Z" }).ToArray() } });
var encountered = OngoingCardData.Encounters(default, Hist(Game(99)), default, "self", "target");
Check("Recent histories merged and deduplicated", encountered.Games.Length == 1);
Check("Latest shared teammate label", encountered.LabelKey == "metLastGameTeammate");
Check("Both heroes and KDA preserved", encountered.Games[0].Self!.ChampionId == 1 && encountered.Games[0].Target!.Kills == 4);
Check("Latest shared enemy label", OngoingCardData.Encounters(default, Hist(Game(99, true)), default, "self", "target").LabelKey == "metLastGameOpponent");
Check("CHERRY subteams define opposite side", OngoingCardData.Encounters(default, Hist(Game(99, cherry: true)), default, "self", "target").Games.Single().IsOpponent == true);
var saved = OngoingCardData.Encounters(Saved(99), Hist(Game(99)), default, "self", "target");
Check("Saved record wins over recent duplicate like upstream", saved.Games.Single().Summary.ValueKind == JsonValueKind.Undefined && saved.Games.Single().Record.Id == 99);
Check("Unresolved saved retains queue/date rather than empty popover", saved.Games.Single().QueueName == "KIWI" && saved.Games.Single().PlayedAt.HasValue);
Check("Unresolved latest saved has generic met label", saved.LabelKey == "met");
var cache = J(new Dictionary<string, object> { ["99"] = Game(99) });
Check("Saved cached details resolve both participants", OngoingCardData.Encounters(Saved(99), Hist(Game(99)), cache, "self", "target").Games.Single().Target!.ChampionId == 2);
Check("Saved record survives cache without target while hiding statistics, as upstream", OngoingCardData.Encounters(Saved(99), default, J(new Dictionary<string, object> { ["99"] = Game(99, missing: true) }), "self", "target").Games is [{ Self: null, Target: null }]);
Check("Only matching target/self games included", OngoingCardData.Encounters(default, Hist(Game(99, missing: true)), default, "self", "target").Games.Length == 0);
var many = OngoingCardData.Encounters(default, Hist(Enumerable.Range(1, 45).Select(i => Game(i)).ToArray()), default, "self", "target");
Check("Original met default page limit is forty", many.Games.Length == 40);
Check("Encounter sort uses actual date descending", many.Games[0].Record.GameId == 45 && many.Games[^1].Record.GameId == 6);
Check("Latest nonshared match prevents last-game label", OngoingCardData.Encounters(default, Hist(Game(100, missing: true), Game(99)), default, "self", "target").LabelKey == "met");
Check("Saved lastMetAt without records remains visible", OngoingCardData.Encounters(J(new { lastMetAt = "2026-10-07T01:00:00Z" }), default, default, "self", "target").LastMetAt.HasValue);
var allTagSettings = J(new Dictionary<string, bool> { ["showAverageTeamDamageTag"] = true, ["showAverageTeamDamageTakenTag"] = true, ["showAverageTeamGoldTag"] = true, ["showAverageCsPerMinuteTag"] = true, ["showAverageDamageGoldEfficiencyTag"] = true, ["showAverageEnemyMissingPingsTag"] = true, ["showAverageVisionScoreTag"] = true, ["showAkariScoreTag"] = true });
JsonElement TagAnalysis(double earlyDeaths = 1.5, double efficiency = 1.36, int n = 20, double rate = .85, int streak = 3) => J(new { count = n, detailsCount = 10, summary = new { avgSoloKills = 1.234, avgChampionDamagePercentageOfTeam = .23456, avgDamageTakenPercentageOfTeam = .34567, avgGoldPercentageOfTeam = .20123, avgCsPerMinute = 7.36, avgCsPercentageOfTeam = .278, avgDamageGoldEfficiency = 1.2345, avgEnemyMissingPings = 0d, avgVisionScore = 12.1234, avgKillDamageEfficiency = efficiency }, winLoss = new { all = new { count = n, wins = 17, winRate = rate, winningStreak = streak, losingStreak = 3 } }, akariScore = new { total = 8.234, extraordinary = true, outstanding = true, kdaScore = .8, winRateScore = .5, dmgScore = 4d, dmgTakenScore = -1d, csScore = 1.2, goldScore = 1d, participationScore = 1.3, visionScore = 1.4 }, spells = new { flashOnD = 3, flashOnF = 7 }, details = new { avgEarlyDeathsWithEnemyJunglerInvolved = earlyDeaths } });
OngoingTag[] Tags(JsonElement a, JsonElement settings = default, bool jungler = false) => OngoingCardTags.Build(settings, a, false, "A", true, jungler);
var tags = Tags(TagAnalysis(), allTagSettings);
Check("All original tag definitions have distinct IDs", OngoingCardTags.Order.Distinct().Count() == 21);
Check("Core tag order preserves original registry ordering", tags.Select(t => t.Id).SequenceEqual(OngoingCardTags.Order.Where(k => k is not "self" and not "tagged" and not "met")));
Check("Tags use actual analyzed win count and threshold", tags.Single(t => t.Id == "high-win-rate").Details[0].Arguments["winCount"]!.Equals(17d));
Check("Under sixteen samples hides high win tag", !Tags(TagAnalysis(n: 15)).Any(t => t.Id == "high-win-rate"));
Check("Below eighty-five percent hides high win tag", !Tags(TagAnalysis(rate: .84999)).Any(t => t.Id == "high-win-rate"));
Check("Under three wins hides streak", !Tags(TagAnalysis(streak: 2)).Any(t => t.Id == "winning-streak"));
Check("No analysis only shows context tags", Tags(default).Select(t => t.Id).SequenceEqual(new[] { "premade-team", "privacy" }));
Check("Self enabled and privacy shown independently of analysis", OngoingCardTags.Build(default, default, true, "", true, false).Select(t => t.Id).SequenceEqual(new[] { "self", "privacy" }));
Check("Original optional statistics defaults hidden", !Tags(TagAnalysis()).Any(t => t.Id == "average-team-damage" || t.Id == "akari-score"));
Check("Explicit settings false overrides runtime predicate", !Tags(TagAnalysis(), J(new { showWinRateTeamTag = false, showPremadeTeamTag = false, showGreatPerformanceTag = false })).Any(t => t.Id is "high-win-rate" or "premade-team" or "great-performance"));
Check("Solo label retains one decimal", tags.Single(t => t.Id == "solo-kills").Label.Arguments["times"]!.Equals("1.2"));
Check("Solo tooltip retains two decimals and analysis sample count", tags.Single(t => t.Id == "solo-kills").Details[0].Arguments["times"]!.Equals("1.23") && tags.Single(t => t.Id == "solo-kills").Details[0].Arguments["count"]!.Equals(20));
Check("Share label rounds percentage to whole integer", tags.Single(t => t.Id == "average-team-damage").Label.Arguments["rate"]!.Equals("23"));
Check("Share tooltip retains precise percentage", tags.Single(t => t.Id == "average-team-damage").Details[0].Arguments["rate"]!.Equals("23.46"));
var cs = tags.Single(t => t.Id == "average-cs-per-minute");
Check("CS per minute original label and tooltip precision", cs.Label.Arguments["value"]!.Equals("7.4") && cs.Details[0].Arguments["value"]!.Equals("7.36"));
Check("CS tooltip includes precise team share", cs.Details[1].Key == "csTeamSharePopover" && cs.Details[1].Arguments["rate"]!.Equals("27.80"));
Check("Damage-gold tooltip includes definition and usage", tags.Single(t => t.Id == "average-damage-gold-efficiency").Details.Select(t => t.Key).SequenceEqual(new[] { "damageGoldEfficiencyPopover", "damageGoldEfficiencyPopoverDefinition", "damageGoldEfficiencyPopoverUsage" }));
Check("Vision label strips trailing zero only and tooltip three decimals", tags.Single(t => t.Id == "average-vision-score").Label.Arguments["count"]!.Equals("12.1") && tags.Single(t => t.Id == "average-vision-score").Details[0].Arguments["count"]!.Equals("12.123"));
Check("Zero missing ping is a valid tag and readable black text", tags.Single(t => t.Id == "average-enemy-missing-pings") is { BlackText: true, Color: "#e7da30" } && tags.Single(t => t.Id == "average-enemy-missing-pings").Label.Arguments["count"]!.Equals("0"));
Check("Absent/null metrics never invent zero tags", !Tags(J(new { summary = new { avgSoloKills = (double?)null, avgEnemyMissingPings = (double?)null } }), allTagSettings).Any(t => t.Id is "solo-kills" or "average-enemy-missing-pings" or "average-team-damage"));
Check("Great-performance prefers extraordinary", tags.Single(t => t.Id == "great-performance").Label.Key == "akariLoved.extraordinary");
Check("Akari numeric label retains original precision", tags.Single(t => t.Id == "akari-score").Label.Key == "$Akari 8.23");
Check("Flash tag exists only when both keys have samples", tags.Any(t => t.Id == "suspicious-flash-position") && !Tags(J(new { summary = new { avgKda = 1 }, spells = new { flashOnD = 0, flashOnF = 7 } })).Any(t => t.Id == "suspicious-flash-position"));
foreach (var (deaths, label) in new[] { (2.01, "veryEasyGank"), (2d, "easyGank"), (1.5, "easyGank"), (1d, "gankable"), (.999, "hardGank"), (0d, "hardGank") }) Check("Easy gank threshold " + deaths, Tags(TagAnalysis(deaths)).Single(t => t.Id == "easy-gank").Label.Key == label);
Check("Current jungler never shows easy gank", !Tags(TagAnalysis(), jungler: true).Any(t => t.Id == "easy-gank"));
Check("Smite on either key or case-insensitive position marks jungler", OngoingCardTags.IsJungler("jungle", default) && OngoingCardTags.IsJungler("TOP", J(new { spell1Id = 11 })) && OngoingCardTags.IsJungler("MIDDLE", J(new { spell2Id = 11 })));
foreach (var boundary in new[] { .65, 1.35 }) Check("Kill damage efficiency excludes exact boundary " + boundary, !Tags(TagAnalysis(efficiency: boundary)).Any(t => t.Id == "average-kill-damage-efficiency"));
Check("Below boundary uses low efficiency", Tags(TagAnalysis(efficiency: .649)).Single(t => t.Id == "average-kill-damage-efficiency").Label.Key == "killDamageEfficiencyLow");
Check("Premade A keeps light/dark contrast", tags.Single(t => t.Id == "premade-team") is { Color: "#0f6f68", DarkColor: "#48e5db", BlackText: false, DarkBlackText: true });
Check("Premade L has distinct original palette rather than six-color cycle", OngoingCardTags.Build(default, default, false, "L", false, false).Single() is { Color: "#333333", DarkColor: "#555555", DarkBlackText: false });
var parts = OngoingCardTags.ScoreParts(TagAnalysis().Field("akariScore"));
Check("Score breakdown original eight components in source order", parts.Select(p => p.Key).SequenceEqual(new[] { "kdaScore", "winRateScore", "dmgScore", "dmgTakenScore", "csScore", "goldScore", "participationScore", "visionScore" }));
Check("Score progress clamped using original caps", parts[2] is { Maximum: 3, Progress: 100 } && parts[3] is { Maximum: 2, Progress: 0 });
Check("Missing score component remains N/A and zero progress", OngoingCardTags.ScoreParts(default).All(p => p.Value == null && p.Progress == 0));
var remake = J(new { gameId = 777, gameCreation = 1700000000000, participants = new[] { new { puuid = "self", championId = 1, teamId = 100, teamPosition = "TOP", gameEndedInEarlySurrender = true, win = false }, new { puuid = "target", championId = 2, teamId = 100, teamPosition = "JUNGLE", gameEndedInEarlySurrender = true, win = false } } });
var remakeEncounter = OngoingCardData.Encounters(default, Hist(remake), default, "self", "target").Games.Single();
Check("Encounter preserves remake instead of flattening to loss", remakeEncounter.Self!.Result == "remake");
Check("Encounter preserves both positions", remakeEncounter.Self!.Position == "TOP" && remakeEncounter.Target!.Position == "JUNGLE");
Check("Great and flash tags require only their source analysis, not a fabricated summary", Tags(J(new { akariScore = new { total = 7d, outstanding = true }, spells = new { flashOnD = 1, flashOnF = 1 } }), allTagSettings).Any(t => t.Id == "great-performance") && Tags(J(new { spells = new { flashOnD = 1, flashOnF = 1 } })).Any(t => t.Id == "suspicious-flash-position"));
Check("Zero solo kills hidden like original truthy gate", !Tags(J(new { summary = new { avgSoloKills = 0d } })).Any(t => t.Id == "solo-kills"));
Check("Null early death statistic hides easy gank", !Tags(J(new { summary = new { avgKda = 1d }, details = new { avgEarlyDeathsWithEnemyJunglerInvolved = (double?)null } })).Any(t => t.Id == "easy-gank"));
Console.WriteLine($"Ongoing card fixtures: {passed} passed");
