export const SMALL_SIZE_THRESHOLD = 1064

export const ENCOUNTERED_GAMES_PAGE_SIZE = 10

export const CHAMPION_MASTERY_TOP_COUNT = 8

export const CHAMPION_MASTERY_SKELETON_COUNT = 4

export const CHAMPION_MASTERY_MODAL_ITEM_SIZE = 56

export const CHALLENGES_CHAMPIONS_ID = 505001

export const CHALLENGES_ASSASSIN_CHAMPIONS_ID = 505002

export const CHALLENGES_FIGHTER_CHAMPIONS_ID = 505003

export const CHALLENGES_MAGE_CHAMPIONS_ID = 505004

export const CHALLENGES_MARKSMAN_CHAMPIONS_ID = 505005

export const CHALLENGES_SUPPORT_CHAMPIONS_ID = 505006

export const CHALLENGES_TANK_CHAMPIONS_ID = 505007

export const CHALLENGES_CHAMPION_SKINS_ID = 510001

export const CHALLENGES_CHROMA_SKINS_ID = 510011

export const CHALLENGES_WARD_SKINS_ID = 504003

export const CHALLENGES_SUMMONER_ICONS_ID = 504002

export const CHALLENGES_EMOTES_ID = 504004

export const CHALLENGES_PEKTAKILLS_ID = 402106
