using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;
using System.Text.Json;
using LeagueAkari.WinUI.Services;
namespace LeagueAkari.WinUI.Pages;

public sealed partial class OngoingPage : UserControl
{
    private readonly BackendClient _backend; private readonly GameAssets _assets; private readonly Action<string, string>? _openPlayer;
    private readonly StackPanel _root = new() { Spacing = 12, Margin = new Thickness(14) }; private readonly TextBlock _status = new(); private readonly StackPanel _teams = new() { Spacing = 20 }; private readonly InfoBar _error = new() { IsClosable = true };
    private Button? _clearDraft; private bool _applyingToolbar; private readonly ComboBox _order = new() { Width = 115 }; private readonly ComboBox _queue = new() { Width = 160 }; private readonly DispatcherTimer _refresh = new() { Interval = TimeSpan.FromMilliseconds(300) };
    private JsonElement _state, _all, _settings, _client, _resources, _sgp; private string _preferredSource = "sgp"; private readonly Dictionary<string, JsonElement> _analysis = []; private readonly Dictionary<string, string> _analysisKeys = []; private readonly Action<string, string, int?, string?>? _collectMatches; private readonly bool _standalone; private int _columns; private string _renderSignature = ""; private bool _refreshing; private bool _subscribed; private string _server = "";
    private readonly Func<bool>? _canPreview; private int _visibilityRevision;
    private bool CanPreview => _subscribed && IsRefreshEnabled && (_canPreview?.Invoke() != false);
    private bool _enabled = true; public bool IsRefreshEnabled { get => _enabled; set { if (_enabled != value) ++_visibilityRevision; _enabled = value; if (!value) _refresh.Stop(); } }
    public OngoingPage(BackendClient backend, Action<string, string>? openPlayer = null, Action<string, string, int?, string?>? collectMatches = null, bool standalone = false, Func<bool>? canPreview = null)
    {
        _canPreview = canPreview; _collectMatches = collectMatches; _standalone = standalone; _backend = backend; _assets = new(backend); _openPlayer = openPlayer;
        var bar = Row(); bar.Children.Add(new TextBlock { Text = Localization.Translate("对局"), FontSize = 24 }); InitializeQueue(); bar.Children.Add(_queue); bar.Children.Add(_order); BuildOrder(); Button(bar, "整队刷新", async () => { await _backend.CallAsync("ongoing-game-main", "reload"); await RefreshAsync(); }); _clearDraft = Button(bar, "结束模拟", async () => { await _backend.CallAsync("ongoing-game-main", "clearDraft"); await RefreshAsync(); }); _root.Children.Add(bar); _root.Children.Add(_status); _root.Children.Add(_error); _root.Children.Add(_teams); Content = new ScrollViewer { Content = _root };
        _refresh.Tick += async (_, _) => { _refresh.Stop(); await RefreshAsync(); }; Loaded += async (_, _) => { _backend.EventReceived -= BackendEvent; _backend.EventReceived += BackendEvent; _subscribed = true; Localization.Changed += AppearanceChanged; if (NativeAppearance.Current is { } appearance) appearance.Changed += AppearanceChanged; await RefreshAsync(); }; Unloaded += (_, _) => { _subscribed = false; ++_visibilityRevision; Localization.Changed -= AppearanceChanged; if (NativeAppearance.Current is { } appearance) appearance.Changed -= AppearanceChanged; _backend.EventReceived -= BackendEvent; _refresh.Stop(); }; SizeChanged += (_, _) => { int next = Columns(); if (next != _columns) { _columns = next; Render(); } };
    }
    private void AppearanceChanged() { SyncToolbar(); _renderSignature = ""; NativeTextBinding.TranslateTree(_root); Render(); }
    private int Columns() => Math.Clamp((int)Math.Floor((ActualWidth - 28) / 240), 1, 8);
    private static string L(string zh, string en) => Localization.Text(zh, en);
    private static StackPanel Row() => new() { Orientation = Orientation.Horizontal, Spacing = 7 };
    private Button Button(Panel panel, string label, Func<Task> action) { var button = new Button { Content = Localization.Translate(label), FontSize = 12 }; button.Click += async (_, _) => { button.IsEnabled = false; await RunAsync(action); button.IsEnabled = true; }; panel.Children.Add(button); return button; }
    private async Task RunAsync(Func<Task> action) { try { await action(); } catch (Exception ex) { _error.Title = ex.Message; _error.IsOpen = true; _error.Severity = InfoBarSeverity.Error; } }
    private void BackendEvent(JsonElement ev) { if (!IsRefreshEnabled) return; string ns = ev.Text("namespace"), name = ev.Text("name"); if (ns == "ongoing-game-main" || name.Contains("ongoing-game-main") || ns == "saved-player-main" || ns == "sgp-main" || ns == "setting-factory-main" || ns == "league-client-main") DispatcherQueue.TryEnqueue(() => { if (!_refresh.IsEnabled) _refresh.Start(); }); }
    public async Task RefreshAsync()
    {
        if (_refreshing || !IsRefreshEnabled) return; _refreshing = true; try
        {
            var results = await Task.WhenAll(_backend.StateAsync("ongoing-game-main"), _backend.CallAsync("ongoing-game-main", "getAll"), _backend.CallAsync("setting-factory-main", "getByPrefix", "ongoing-game-main", ""), _backend.StateAsync("league-client-main"), _backend.StateAsync("sgp-main"), _backend.StateAsync("league-client-main", "gameData"), _backend.CallAsync("setting-factory-main", "get", "app-common-main", "preferredLolSource")); _state = results[0]; _all = results[1]; _settings = results[2]; _client = results[3]; _server = results[4].Field("availability").Text("sgpServerId"); _resources = results[5]; _sgp = results[4]; _preferredSource = results[6].ValueKind == JsonValueKind.String ? results[6].GetString() ?? "sgp" : "sgp"; await LoadAnalysesAsync(); SyncToolbar(); Render();
        }
        catch (Exception ex) { _error.Title = ex.Message; _error.IsOpen = true; }
        finally { _refreshing = false; }
    }
    private void Render()
    {
        if (!IsRefreshEnabled || _state.ValueKind != JsonValueKind.Object) return; var signature = _state.GetRawText() + _all.GetRawText() + _settings.GetRawText() + Localization.Locale + Private + Columns() + JsonSerializer.Serialize(_analysis); if (signature == _renderSignature) return; _renderSignature = signature; var stage = _state.Field("queryStage"); _status.Text = stage.Text("phase") switch { "champ-select" => L("英雄选择", "Champion select"), "in-game" => L("游戏进行中", "In game"), "lobby" => L("组队大厅", "Lobby"), _ => L("等待对局", "Waiting for game") }; if (stage.Text("phase") == "unavailable") _status.Text = !Setting("enabled", true) ? K("panel.disabled") : _client.Text("connectionState") != "connected" ? K("panel.disconnected") : _client.Field("champSelect").Field("session").Boolean("isSpectating") ? K("panel.waitingForSpectate") : K("panel.noOngoingGame"); if (_state.Field("draft").ValueKind == JsonValueKind.Object) _status.Text += L(" · 模拟对局", " · simulation"); _teams.Children.Clear(); var teams = _state.Field("teams"); if (teams.ValueKind != JsonValueKind.Object) return;
        int columns = Columns(); foreach (var team in teams.EnumerateObject()) { var ids = team.Value.Items().Select(v => v.GetString() ?? "").Distinct().Where(id => id.Length > 0).ToArray(); if (ids.Length == 0) continue; ids = OrderPlayers(ids); var summaries = ids.Select(id => MatchData.Summarize(History(id), id)).ToArray(); var section = new StackPanel { Spacing = 8 }; string title = team.Name switch { "TEAM-100" => L("● 蓝队", "● Blue team"), "TEAM-200" => L("● 红队", "● Red team"), "TEAM-ALL" => L("全部玩家", "All players"), _ => L("组队大厅", "Lobby") }; section.Children.Add(new TextBlock { Text = $"{title}   {summaries.Sum(s => s.Wins) / (double)Math.Max(1, summaries.Sum(s => s.Count)):P0} · KDA {OngoingCardData.TeamKda(summaries):F2}", FontSize = 17, FontWeight = Microsoft.UI.Text.FontWeights.Bold }); section.Children.Add(TeamChips(ids)); var grid = new Grid { ColumnSpacing = 7, RowSpacing = 7 }; for (int c = 0; c < columns; c++) grid.ColumnDefinitions.Add(new() { Width = new GridLength(1, GridUnitType.Star) }); for (int r = 0; r < (ids.Length + columns - 1) / columns; r++) grid.RowDefinitions.Add(new() { Height = GridLength.Auto }); for (int i = 0; i < ids.Length; i++) { var card = PlayerCard(ids[i]); Grid.SetColumn(card, i % columns); Grid.SetRow(card, i / columns); grid.Children.Add(card); } section.Children.Add(grid); _teams.Children.Add(section); }
        NativeTextBinding.TranslateTree(_root);
    }
    private JsonElement[] History(string id) => _all.Field("matchHistory").Field(id).Field("data").Items().Select(MatchData.Game).ToArray();
    private FrameworkElement PlayerCard(string id)
    {
        var summoner = _all.Field("summoner").Field(id); var games = History(id); var summary = MatchData.Summarize(games, id); var card = new StackPanel { Spacing = 5, Margin = new Thickness(8) }; var header = Row(); int champ = (int)_state.Field("championSelections").Field(id).TryNumber(); int icon = (int)summoner.Number("profileIconId"); var portrait = new Button { Content = _assets.Icon(champ > 0 ? "champion-summary" : "profile-icons", champ > 0 ? champ : icon, 36), Padding = new Thickness(0), BorderThickness = new Thickness(0), IsEnabled = _openPlayer != null }; portrait.Click += (_, _) => _openPlayer?.Invoke(id, _server); header.Children.Add(portrait); var identity = new StackPanel { Spacing = 2 }; string name = summoner.Text("gameName", summoner.Text("displayName", id[..Math.Min(8, id.Length)])); var nameButton = new Button { Content = new TextBlock { Text = PrivacyName(id, name, summoner.Text("tagLine")), FontWeight = Microsoft.UI.Text.FontWeights.Bold, TextTrimming = TextTrimming.CharacterEllipsis, MaxWidth = 170 }, Padding = new Thickness(0), BorderThickness = new Thickness(0), IsEnabled = _openPlayer != null }; nameButton.Click += (_, _) => _openPlayer?.Invoke(id, _server); identity.Children.Add(nameButton); identity.Children.Add(new TextBlock { Text = $"{summoner.Number("summonerLevel")} · {Localization.Key("common.positions." + Position(id), Position(id))}", FontSize = 11 }); header.Children.Add(identity); card.Children.Add(header);
        card.Children.Add(RankSummary(id)); card.Children.Add(PlayerStats(id, games, summary));
        var badges = BuildBadges(id); card.Children.Add(badges); if (_settings.Text("showChampionUsage", "recent") != "none") card.Children.Add(Usage(id, summary));
        var analysis = _analysis.GetValueOrDefault(id); if (Setting("showJunglePathing", true) && (IsJungler(id) || Setting("showJunglePathingForAllPlayers", false)) && analysis.Field("jungle").ValueKind == JsonValueKind.Object) card.Children.Add(new JunglePathingView(_assets, analysis, champ));
        int count = (int)_settings.Number("matchHistoryLoadCount", 50); var rows = new StackPanel { Spacing = 3 }; foreach (var game in games.Take(count)) { var p = MatchData.Self(game, id); if (p is null) continue; var rowColors = NativeMatchColors.Ongoing(game.Text("gameMode") == "PRACTICETOOL" ? "neutral" : p.WinResult, NativeAppearance.Current?.IsDark ?? ActualTheme == ElementTheme.Dark); var row = Row(); row.Children.Add(_assets.Icon("champion-summary", p.ChampionId, 24)); var text = new TextBlock { Text = $"{QueueName((int)game.Number("queueId"))}\n{MatchData.Creation(game).ToLocalTime():MM-dd HH:mm} · {MatchResult(game, p)}", FontSize = 10, Width = 90, Foreground = MatchBrush(rowColors.Result) }; row.Children.Add(text); row.Children.Add(new TextBlock { Text = $"{p.Kills}/{p.Deaths}/{p.Assists}", FontSize = 11, VerticalAlignment = VerticalAlignment.Center }); var open = new Button { Content = row, Padding = new Thickness(3), HorizontalAlignment = HorizontalAlignment.Stretch, HorizontalContentAlignment = HorizontalAlignment.Left, BorderThickness = new Thickness(Setting("showMatchHistoryItemBorder", false) ? 1 : 0), BorderBrush = MatchBrush(rowColors.Border), Background = MatchBrush(rowColors.Background) }; open.Click += async (_, _) => await RunAsync(async () => { await PreviewMatchAsync(id, (long)game.Number("gameId")); }); rows.Children.Add(open); }
        var loading = _state.Field("matchHistoryLoadingState").Text(id); if (loading == "loading") rows.Children.Add(new ProgressRing { IsActive = true, Width = 20, Height = 20 }); if (loading == "error") { rows.Children.Add(new TextBlock { Text = K("playerCard.errorLoadingMatchHistory"), FontSize = 11 }); Button(rows, L("重试", "Retry"), async () => { await _backend.CallAsync("ongoing-game-main", "reloadPlayer", id); await RefreshAsync(); }); }
        if (rows.Children.Count == 0) rows.Children.Add(new TextBlock { Text = K("playerCard.empty"), FontSize = 11 }); card.Children.Add(new ScrollViewer { Content = rows, MaxHeight = 250 });
        var actions = Row(); if (_openPlayer is not null) Button(actions, "战绩", () => { _openPlayer(id, _server); return Task.CompletedTask; }); Button(actions, "刷新", async () => { await _backend.CallAsync("ongoing-game-main", "reloadPlayer", id, new { includes = new[] { "matchHistory", "rankedStats", "savedInfo", "championMastery" } }); await RefreshAsync(); }); if (!_standalone && id != SelfPuuid && SelfPuuid != "") Button(actions, "标记", () => EditTagAsync(id, PrivacyName(id, name))); if (!_standalone) { var more = new Button { Content = "⋮", Flyout = CardActions(id) }; actions.Children.Add(more); }
        card.Children.Add(actions); var outer = new Border { Child = card, BorderThickness = new Thickness(1), CornerRadius = new(6), BorderBrush = new SolidColorBrush(PremadeColor(Premade(id))) }; outer.ContextFlyout = CardActions(id); return outer;
    }
}


